In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from itertools import combinations
from rtree import index
import matplotlib.pyplot as plt
import seaborn as sns
import time

T1 = time.time()

# 指定分号为字段分隔符
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/4-2/03870.csv', sep=';') 
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/M3353_gpsdistance_normalized(2).csv') #20条
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/M3353_gpsdistance_normalized(2).csv') #10条
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/datas/20/M2503_gpsdistance_normalized.csv') #10条
fdata = pd.read_csv('E:/大数据/毕业设计/数据/datas/40/M2333_gpsdistance_normalized.csv') #10条
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/datas/10/M5583_gpsdistance_normalized.csv') #10条
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/4-2/M2333.csv', sep=';')  #40条
#fdata = pd.read_csv('E:/大数据/毕业设计/数据/result/M4123_dropdata.csv')   #10条
display(fdata)

,idx,opath,lineName,direction,t_flag,time,lng,lat,distance_of_gpspoint,gps_normalized_distance_length
0,BS04317D,63083,M2333,1.0,1,2019-01-04 07:03:27,113.906742,22.709049,0.432755,0.010337
1,BS04317D,63083,M2333,1.0,1,2019-01-04 07:36:46,113.906392,22.709334,0.480602,0.011480
2,BS04317D,63083,M2333,1.0,1,2019-01-04 07:36:56,113.906379,22.709346,0.482525,0.011526
3,BS04317D,63083,M2333,1.0,1,2019-01-04 07:37:06,113.906344,22.709380,0.487659,0.011649
4,BS04317D,63083,M2333,1.0,1,2019-01-04 07:47:36,113.906416,22.709311,0.477055,0.011396
...,...,...,...,...,...,...,...,...,...,...
130962,BS08123D,75772,M2333,2.0,3,2019-01-04 16:05:15,113.904974,22.710708,41.662506,0.966983
130963,BS08123D,75771,M2333,2.0,3,2019-01-04 16:05:25,113.906310,22.709231,41.892125,0.972313
130964,BS08123D,75771,M2333,2.0,3,2019-01-04 16:05:35,113.906427,22.709129,41.908692,0.972697
130965,BS08123D,75771,M2333,2.0,3,2019-01-04 16:17:45,113.906521,22.709055,41.921378,0.972992
130966,BS08123D,75771,M2333,2.0,3,2019-01-04 16:17:55,113.906564,22.709021,41.927184,0.973127

In [2]:
import pandas as pd

# 定义 assign_to_windows 函数
def assign_to_windows(row):
    current_time = row['time']
    minutes_since_midnight = (current_time - current_time.normalize()).total_seconds() / 60.0
    
    # 计算基本时间窗口的开始时间，确保每个窗口覆盖4分钟
    window_start_minute = int(minutes_since_midnight // 4 * 4)  # 使用整除并乘以4确保步进为4
    window_end_minute = window_start_minute + 4  # 窗口结束时间调整为开始时间后的4分钟
    
    return pd.Series([window_start_minute, window_end_minute])

# 将 'time' 列的数据类型从字符串转换为 datetime
fdata['time'] = pd.to_datetime(fdata['time'])

# 应用函数，并创建新的列来存储分配结果
fdata[['win_st', 'win_en']] = fdata.apply(assign_to_windows, axis=1)

In [3]:
# 基于车牌号（'idx'列）、线路号（'linenumber'列）和时间窗口的开始时间（'win_st'列）对数据进行分组
counts_per_group = fdata.groupby(['lineName', 'idx', 'win_st']).size()

# 过滤掉那些在同一时间窗口内每组只有一条记录的数据
# 这会返回一个包含每组在每个时间窗口内记录数大于1的过滤后的DataFrame的索引
filtered_idx = counts_per_group[counts_per_group > 1].index

# 基于过滤后的索引，我们选择原始数据集中符合条件的行
# 这里的'linenumber', 'idx'和'win_st'必须与groupby中使用的列名完全匹配
fdata_filtered = fdata[fdata.set_index(['lineName', 'idx', 'win_st']).index.isin(filtered_idx)]

display(fdata_filtered)

,idx,opath,lineName,direction,t_flag,time,lng,lat,distance_of_gpspoint,gps_normalized_distance_length,win_st,win_en
1,BS04317D,63083,M2333,1.0,1,2019-01-04 07:36:46,113.906392,22.709334,0.480602,0.011480,456,460
2,BS04317D,63083,M2333,1.0,1,2019-01-04 07:36:56,113.906379,22.709346,0.482525,0.011526,456,460
3,BS04317D,63083,M2333,1.0,1,2019-01-04 07:37:06,113.906344,22.709380,0.487659,0.011649,456,460
4,BS04317D,63083,M2333,1.0,1,2019-01-04 07:47:36,113.906416,22.709311,0.477055,0.011396,464,468
5,BS04317D,63083,M2333,1.0,1,2019-01-04 07:47:46,113.906424,22.709304,0.475932,0.011369,464,468
...,...,...,...,...,...,...,...,...,...,...,...,...
130962,BS08123D,75772,M2333,2.0,3,2019-01-04 16:05:15,113.904974,22.710708,41.662506,0.966983,964,968
130963,BS08123D,75771,M2333,2.0,3,2019-01-04 16:05:25,113.906310,22.709231,41.892125,0.972313,964,968
130964,BS08123D,75771,M2333,2.0,3,2019-01-04 16:05:35,113.906427,22.709129,41.908692,0.972697,964,968
130965,BS08123D,75771,M2333,2.0,3,2019-01-04 16:17:45,113.906521,22.709055,41.921378,0.972992,976,980
130966,BS08123D,75771,M2333,2.0,3,2019-01-04 16:17:55,113.906564,22.709021,41.927184,0.973127,976,980

In [4]:
# 计算每辆车每个时间窗口的MBR
def calculate_mbrs(group):
    min_time = group['time'].min()
    max_time = group['time'].max()
    min_dis_location = group['gps_normalized_distance_length'].min()
    max_dis_location = group['gps_normalized_distance_length'].max()
    return pd.Series([min_time, max_time, min_dis_location, max_dis_location], index=['min_time', 'max_time', 'min_dis_location', 'max_dis_location'])

# 按 idx 和 win_st 分组，计算 MBR
mbrs = fdata_filtered.groupby(['idx', 'win_st']).apply(calculate_mbrs)
mbrs.reset_index(inplace=True)

# 将时间转换为时间戳
mbrs["min_timestamp"] = mbrs["min_time"].apply(lambda x: int(x.timestamp()))
mbrs["max_timestamp"] = mbrs["max_time"].apply(lambda x: int(x.timestamp()))

# 创建 R-Tree 索引
p = index.Property()
Mbr_Tree = index.Index(properties=p)

# 添加 MBR 到 R-Tree 索引
for mbr in mbrs.itertuples():
    Mbr_Tree.insert(mbr.Index, (mbr.min_timestamp, mbr.min_dis_location, mbr.max_timestamp, mbr.max_dis_location))

# 查找相交的 MBR
def find_intersections(mbrs, Mbr_Tree):
    intersection_pairs = []
    for mbr in mbrs.itertuples():
        intersecting_mbrs = list(Mbr_Tree.intersection((mbr.min_timestamp, mbr.min_dis_location, mbr.max_timestamp, mbr.max_dis_location), objects=True))
        for inter in intersecting_mbrs:
            if mbr.Index < inter.id:  # 防止重复对比
                intersection_pairs.append((mbr.Index, inter.id))
    return intersection_pairs

# 定义检查两个MBR是否相交的函数
def mbrs_intersect(mbr1, mbr2):
    return not (mbr1['max_timestamp'] < mbr2['min_timestamp'] or mbr1['min_timestamp'] > mbr2['max_timestamp'] or
                mbr1['max_dis_location'] < mbr2['min_dis_location'] or mbr1['min_dis_location'] > mbr2['max_dis_location'])

# 辅助函数，计算两点确定的直线的参数（斜率和截距）
def calculate_line_parameters(point1, point2):
    x_coords, y_coords = [point1[0], point2[0]], [point1[1], point2[1]]
    A = np.vstack([x_coords, np.ones(len(x_coords))]).T
    m, c = np.linalg.lstsq(A, y_coords, rcond=None)[0]
    return m, c

# 辅助函数，计算点到直线的距离
def point_to_line_distance(point, line_points):
    x0, y0 = point
    x1, y1 = line_points[0]
    x2, y2 = line_points[1]
    m, c = calculate_line_parameters((x1, y1), (x2, y2))
    A, B, C = -m, 1, -c
    distance = abs(A * x0 + B * y0 + C) / (np.sqrt(A**2 + B**2))
    return distance

# 函数，计算两条线段之间的最大垂直距离
def calculate_max_vertical_distance_between_lines(line1_points, line2_points):
    point1_line2, point2_line2, midpoint_line2 = line2_points
    distance_start = point_to_line_distance(point1_line2, line1_points)
    distance_mid = point_to_line_distance(midpoint_line2, line1_points)
    distance_end = point_to_line_distance(point2_line2, line1_points)
    return max(distance_start, distance_mid, distance_end)

# 计算串车事件
def detect_bus_bunching(data, intersection_pairs, threshold):
    bunching_events = []

    for (idx1, idx2) in intersection_pairs:
        mbr1 = mbrs.iloc[idx1]
        mbr2 = mbrs.iloc[idx2]

        if mbrs_intersect(mbr1, mbr2):
            line1_points = [(mbr1['min_timestamp'], mbr1['min_dis_location']), (mbr1['max_timestamp'], mbr1['max_dis_location'])]
            line2_points = [(mbr2['min_timestamp'], mbr2['min_dis_location']), (mbr2['max_timestamp'], mbr2['max_dis_location'])]
            midpoint_line2 = ((line2_points[0][0] + line2_points[1][0]) / 2, (line2_points[0][1] + line2_points[1][1]) / 2)
            distance = calculate_max_vertical_distance_between_lines(line1_points, [line2_points[0], midpoint_line2, line2_points[1]])
            
            T2 = time.time()
            print('程序运行时间:%s秒' % ((T2 - T1)*1))
            # 计算串车持续时间
            min_time = min(mbr1['min_time'], mbr2['min_time'])
            max_time = max(mbr1['max_time'], mbr2['max_time'])
            duration = max_time - min_time

            if distance < threshold:
                bunching_events.append({
                    'lineName': data.iloc[idx1]['lineName'],
                    'direction': data.iloc[idx1]['direction'],
                    'idx1': data.iloc[idx1]['idx'],
                    'idx2': data.iloc[idx2]['idx'],
                    'win_st': data.iloc[idx1]['win_st'],
                    'distance': distance,
                    'start_time': min_time,
                    'end_time': max_time,
                    'duration': duration
                })

    return pd.DataFrame(bunching_events)

# 查找相交的 MBR
intersection_pairs = find_intersections(mbrs, Mbr_Tree)

# 检测公交车串车
threshold = 0.01
bunching_df = detect_bus_bunching(fdata_filtered, intersection_pairs, threshold)

def merge_bunching_events(events):
    events = events.sort_values(by='win_st').reset_index(drop=True)
    merged_events = []
    i = 0

    while i < len(events):
        current_event = events.iloc[i]
        j = i + 1

        while j < len(events):
            next_event = events.iloc[j]
            if (current_event['idx1'] == next_event['idx1'] and current_event['idx2'] == next_event['idx2'] and
                (next_event['start_time'] - current_event['end_time']).total_seconds() < 5):
                current_event['end_time'] = next_event['end_time']
                current_event['duration'] = current_event['end_time'] - current_event['start_time']
                current_event['win_st'] = f"{current_event['win_st']},{next_event['win_st']}"
                j += 1
            else:
                break

        merged_events.append(current_event)
        i = j

    merged_df = pd.DataFrame(merged_events)
    # 过滤掉持续时间小于3分钟的事件
    filtered_merged_df = merged_df[merged_df['duration'] >= timedelta(minutes=3)]
    return filtered_merged_df

# 合并串车事件
merged_bunching_df = merge_bunching_events(bunching_df)

# 输出合并后的串车事件
print(merged_bunching_df)

程序运行时间:20.71381688117981秒
程序运行时间:20.71381688117981秒
程序运行时间:20.714824676513672秒
程序运行时间:20.714824676513672秒
程序运行时间:20.714824676513672秒
程序运行时间:20.716058254241943秒
程序运行时间:20.716058254241943秒
程序运行时间:20.716830492019653秒
程序运行时间:20.716830492019653秒
程序运行时间:20.717830657958984秒
程序运行时间:20.717830657958984秒
程序运行时间:20.717830657958984秒
程序运行时间:20.718831300735474秒
程序运行时间:20.718831300735474秒
程序运行时间:20.719831228256226秒
程序运行时间:20.719831228256226秒
程序运行时间:20.72083330154419秒
程序运行时间:20.72083330154419秒
程序运行时间:20.72083330154419秒
程序运行时间:20.72183132171631秒
程序运行时间:20.722831964492798秒
程序运行时间:20.722831964492798秒
程序运行时间:20.722831964492798秒
程序运行时间:20.7238552570343秒
程序运行时间:20.7238552570343秒
程序运行时间:20.724832773208618秒
程序运行时间:20.724832773208618秒
程序运行时间:20.72583246231079秒
程序运行时间:20.72583246231079秒
程序运行时间:20.7268328666687秒
程序运行时间:20.7268328666687秒
程序运行时间:20.7268328666687秒
程序运行时间:20.72807812690735秒
程序运行时间:20.72807812690735秒
程序运行时间:20.728833198547363秒
程序运行时间:20.728833198547363秒
程序运行时间:20.729820489883423秒
程序运行时间:20.729820489883423秒
程序运行时间:20.730833768844604秒
程序运行时间:20.730833768844604秒
程序运行时间:20.731833696365356秒
程序运行时间:20.731833696365356秒
程序运行时间:20.731833696365356秒
程序运行时间:20.732834100723267秒
程序运行时间:20.732834100723267秒
程序运行时间:20.733834505081177秒
程序运行时间:20.733834505081177秒
程序运行时间:20.734835386276245秒
程序运行时间:20.734835386276245秒
程序运行时间:20.73583459854126秒
程序运行时间:20.73583459854126秒
程序运行时间:20.736828804016113秒
程序运行时间:20.736828804016113秒
程序运行时间:20.7378351688385秒
程序运行时间:20.7378351688385秒
程序运行时间:20.7378351688385秒
程序运行时间:20.73883557319641秒
程序运行时间:20.73883557319641秒
程序运行时间:20.73983645439148秒
程序运行时间:20.73983645439148秒
程序运行时间:20.73983645439148秒
程序运行时间:20.740836143493652秒
程序运行时间:20.740836143493652秒
程序运行时间:20.741836309432983秒
程序运行时间:20.741836309432983秒
程序运行时间:20.741836309432983秒
程序运行时间:20.742836475372314秒
程序运行时间:20.742836475372314秒
程序运行时间:20.743836641311646秒
程序运行时间:20.743836641311646秒
程序运行时间:20.743836641311646秒
程序运行时间:20.744848489761353秒
程序运行时间:20.744848489761353秒
程序运行时间:20.74583101272583秒
程序运行时间:20.74583101272583秒
程序运行时间:20.74583101272583秒
程序运行时间:20.74683690071106秒
程序运行时间:20.74683690071106秒
程序运行时间:20.74783205986023秒
程序运行时间:20.74783205986023秒
程序运行时间:20.74783205986023秒
程序运行时间:20.748892307281494秒
程序运行时间:20.748892307281494秒
程序运行时间:20.749831914901733秒
程序运行时间:20.749831914901733秒
程序运行时间:20.750825881958008秒
程序运行时间:20.750825881958008秒
程序运行时间:20.750825881958008秒
程序运行时间:20.751832723617554秒
程序运行时间:20.751832723617554秒
程序运行时间:20.752845764160156秒
程序运行时间:20.752845764160156秒
程序运行时间:20.752845764160156秒
程序运行时间:20.753832817077637秒
程序运行时间:20.753832817077637秒
程序运行时间:20.754839181900024秒
程序运行时间:20.754839181900024秒
程序运行时间:20.75583577156067秒
程序运行时间:20.75583577156067秒
程序运行时间:20.75583577156067秒
程序运行时间:20.75683355331421秒
程序运行时间:20.75683355331421秒
程序运行时间:20.75783944129944秒
程序运行时间:20.75783944129944秒
程序运行时间:20.75783944129944秒
程序运行时间:20.75883984565735秒
程序运行时间:20.75883984565735秒
程序运行时间:20.75883984565735秒
程序运行时间:20.76003670692444秒
程序运行时间:20.76003670692444秒
程序运行时间:20.760834455490112秒
程序运行时间:20.760834455490112秒
程序运行时间:20.760834455490112秒
程序运行时间:20.761945009231567秒
程序运行时间:20.761945009231567秒
程序运行时间:20.762834787368774秒
程序运行时间:20.762834787368774秒
程序运行时间:20.763841152191162秒
程序运行时间:20.763841152191162秒
程序运行时间:20.763841152191162秒
程序运行时间:20.764841318130493秒
程序运行时间:20.765841245651245秒
程序运行时间:20.765841245651245秒
程序运行时间:20.765841245651245秒
程序运行时间:20.766841888427734秒
程序运行时间:20.766841888427734秒
程序运行时间:20.767841815948486秒
程序运行时间:20.767841815948486秒
程序运行时间:20.768842220306396秒
程序运行时间:20.768842220306396秒
程序运行时间:20.768842220306396秒
程序运行时间:20.76983666419983秒
程序运行时间:20.76983666419983秒
程序运行时间:20.76983666419983秒
程序运行时间:20.771044969558716秒
程序运行时间:20.771044969558716秒
程序运行时间:20.771836757659912秒
程序运行时间:20.771836757659912秒
程序运行时间:20.771836757659912秒
程序运行时间:20.77304482460022秒
程序运行时间:20.77304482460022秒
程序运行时间:20.773837327957153秒
程序运行时间:20.773837327957153秒
程序运行时间:20.773837327957153秒
程序运行时间:20.774916887283325秒
程序运行时间:20.774916887283325秒
程序运行时间:20.775837659835815秒
程序运行时间:20.776843786239624秒
程序运行时间:20.776843786239624秒
程序运行时间:20.776843786239624秒
程序运行时间:20.777838230133057秒
程序运行时间:20.777838230133057秒
程序运行时间:20.778844356536865秒
程序运行时间:20.778844356536865秒
程序运行时间:20.778844356536865秒
程序运行时间:20.779844522476196秒
程序运行时间:20.779844522476196秒
程序运行时间:20.780844926834106秒
程序运行时间:20.780844926834106秒
程序运行时间:20.780844926834106秒
程序运行时间:20.78184485435486秒
程序运行时间:20.782845735549927秒
程序运行时间:20.7838454246521秒
程序运行时间:20.7838454246521秒
程序运行时间:20.78484010696411秒
程序运行时间:20.78484010696411秒
程序运行时间:20.78584599494934秒
程序运行时间:20.78584599494934秒
程序运行时间:20.78584599494934秒
程序运行时间:20.786846160888672秒
程序运行时间:20.787846326828003秒
程序运行时间:20.787846326828003秒
程序运行时间:20.787846326828003秒
程序运行时间:20.788848638534546秒
程序运行时间:20.788848638534546秒
程序运行时间:20.789846897125244秒
程序运行时间:20.789846897125244秒
程序运行时间:20.789846897125244秒
程序运行时间:20.790848970413208秒
程序运行时间:20.790848970413208秒
程序运行时间:20.791846990585327秒
程序运行时间:20.791846990585327秒
程序运行时间:20.791846990585327秒
程序运行时间:20.792847633361816秒
程序运行时间:20.792847633361816秒
程序运行时间:20.79384183883667秒
程序运行时间:20.79384183883667秒
程序运行时间:20.79384183883667秒
程序运行时间:20.79484796524048秒
程序运行时间:20.79484796524048秒
程序运行时间:20.79584813117981秒
程序运行时间:20.79584813117981秒
程序运行时间:20.79584813117981秒
程序运行时间:20.79683494567871秒
程序运行时间:20.79683494567871秒
程序运行时间:20.79784893989563秒
程序运行时间:20.798837661743164秒
程序运行时间:20.799837112426758秒
程序运行时间:20.799837112426758秒
程序运行时间:20.800836324691772秒
程序运行时间:20.800836324691772秒
程序运行时间:20.801836729049683秒
程序运行时间:20.801836729049683秒
程序运行时间:20.802836894989014秒
程序运行时间:20.802836894989014秒
程序运行时间:20.803837060928345秒
程序运行时间:20.804837226867676秒
程序运行时间:20.804837226867676秒
程序运行时间:20.805837392807007秒
程序运行时间:20.805837392807007秒
程序运行时间:20.806837797164917秒
程序运行时间:20.806837797164917秒
程序运行时间:20.807838201522827秒
程序运行时间:20.807838201522827秒
程序运行时间:20.80883812904358秒
程序运行时间:20.809839725494385秒
程序运行时间:20.810845613479614秒
程序运行时间:20.810845613479614秒
程序运行时间:20.811845779418945秒
程序运行时间:20.81284213066101秒
程序运行时间:20.81384038925171秒
程序运行时间:20.814839839935303秒
程序运行时间:20.814839839935303秒
程序运行时间:20.815839767456055秒
程序运行时间:20.815839767456055秒
程序运行时间:20.816839933395386秒
程序运行时间:20.816839933395386秒
程序运行时间:20.817840099334717秒
程序运行时间:20.817840099334717秒
程序运行时间:20.818840503692627秒
程序运行时间:20.818840503692627秒
程序运行时间:20.81984043121338秒
程序运行时间:20.81984043121338秒
程序运行时间:20.82084059715271秒
程序运行时间:20.82084059715271秒
程序运行时间:20.82184076309204秒
程序运行时间:20.822840929031372秒
程序运行时间:20.822840929031372秒
程序运行时间:20.82384157180786秒
程序运行时间:20.82384157180786秒
程序运行时间:20.824841737747192秒
程序运行时间:20.824841737747192秒
程序运行时间:20.825841903686523秒
程序运行时间:20.825841903686523秒
程序运行时间:20.826842069625854秒
程序运行时间:20.826842069625854秒
程序运行时间:20.827842235565186秒
程序运行时间:20.827842235565186秒
程序运行时间:20.828842401504517秒
程序运行时间:20.828842401504517秒
程序运行时间:20.829842567443848秒
程序运行时间:20.83085060119629秒
程序运行时间:20.83085060119629秒
程序运行时间:20.83085060119629秒
程序运行时间:20.831850290298462秒
程序运行时间:20.831850290298462秒
程序运行时间:20.831850290298462秒
程序运行时间:20.83285641670227秒
程序运行时间:20.83285641670227秒
程序运行时间:20.83385682106018秒
程序运行时间:20.83385682106018秒
程序运行时间:20.83385682106018秒
程序运行时间:20.83485698699951秒
程序运行时间:20.83485698699951秒
程序运行时间:20.835857391357422秒
程序运行时间:20.835857391357422秒
程序运行时间:20.835857391357422秒
程序运行时间:20.836857318878174秒
程序运行时间:20.836857318878174秒
程序运行时间:20.837857484817505秒
程序运行时间:20.837857484817505秒
程序运行时间:20.838857650756836秒
程序运行时间:20.838857650756836秒
程序运行时间:20.839858531951904秒
程序运行时间:20.839858531951904秒
程序运行时间:20.839858531951904秒
程序运行时间:20.840858221054077秒
程序运行时间:20.840858221054077秒
程序运行时间:20.84185814857483秒
程序运行时间:20.84185814857483秒
程序运行时间:20.84185814857483秒
程序运行时间:20.84285879135132秒
程序运行时间:20.84285879135132秒
程序运行时间:20.84385871887207秒
程序运行时间:20.84385871887207秒
程序运行时间:20.84385871887207秒
程序运行时间:20.84485912322998秒
程序运行时间:20.84485912322998秒
程序运行时间:20.84585928916931秒
程序运行时间:20.84585928916931秒
程序运行时间:20.846847772598267秒
程序运行时间:20.846847772598267秒
程序运行时间:20.846847772598267秒
程序运行时间:20.84785485267639秒
程序运行时间:20.84785485267639秒
程序运行时间:20.848854064941406秒
程序运行时间:20.849854230880737秒
程序运行时间:20.849854230880737秒
程序运行时间:20.850860834121704秒
程序运行时间:20.850860834121704秒
程序运行时间:20.850860834121704秒
程序运行时间:20.851860761642456秒
程序运行时间:20.852850437164307秒
程序运行时间:20.852850437164307秒
程序运行时间:20.853862524032593秒
程序运行时间:20.853862524032593秒
程序运行时间:20.854856491088867秒
程序运行时间:20.854856491088867秒
程序运行时间:20.855857372283936秒
程序运行时间:20.85686206817627秒
程序运行时间:20.85686206817627秒
程序运行时间:20.85686206817627秒
程序运行时间:20.857856512069702秒
程序运行时间:20.857856512069702秒
程序运行时间:20.858862161636353秒
程序运行时间:20.858862161636353秒
程序运行时间:20.858862161636353秒
程序运行时间:20.85986304283142秒
程序运行时间:20.85986304283142秒
程序运行时间:20.860862970352173秒
程序运行时间:20.86186408996582秒
程序运行时间:20.86186408996582秒
程序运行时间:20.86186408996582秒
程序运行时间:20.862857341766357秒
程序运行时间:20.862857341766357秒
程序运行时间:20.863863229751587秒
程序运行时间:20.863863229751587秒
程序运行时间:20.864863634109497秒
程序运行时间:20.865863800048828秒
程序运行时间:20.865863800048828秒
程序运行时间:20.865863800048828秒
程序运行时间:20.86686420440674秒
程序运行时间:20.86786437034607秒
程序运行时间:20.86786437034607秒
程序运行时间:20.868865251541138秒
程序运行时间:20.868865251541138秒
程序运行时间:20.86986517906189秒
程序运行时间:20.86986517906189秒
程序运行时间:20.87086510658264秒
程序运行时间:20.87086510658264秒
程序运行时间:20.87086510658264秒
程序运行时间:20.871865272521973秒
程序运行时间:20.871865272521973秒
程序运行时间:20.872865438461304秒
程序运行时间:20.872865438461304秒
程序运行时间:20.873865842819214秒
程序运行时间:20.873865842819214秒
程序运行时间:20.874865770339966秒
程序运行时间:20.874865770339966秒
程序运行时间:20.874865770339966秒
程序运行时间:20.875865936279297秒
程序运行时间:20.875865936279297秒
程序运行时间:20.876866340637207秒
程序运行时间:20.876866340637207秒
程序运行时间:20.876866340637207秒
程序运行时间:20.877866744995117秒
程序运行时间:20.877866744995117秒
程序运行时间:20.877866744995117秒
程序运行时间:20.87886667251587秒
程序运行时间:20.87886667251587秒
程序运行时间:20.8798668384552秒
程序运行时间:20.8798668384552秒
程序运行时间:20.8798668384552秒
程序运行时间:20.88086724281311秒
程序运行时间:20.88086724281311秒
程序运行时间:20.88186740875244秒
程序运行时间:20.88186740875244秒
程序运行时间:20.88186740875244秒
程序运行时间:20.882867574691772秒
程序运行时间:20.882867574691772秒
程序运行时间:20.883867740631104秒
程序运行时间:20.883867740631104秒
程序运行时间:20.883867740631104秒
程序运行时间:20.884868144989014秒
程序运行时间:20.884868144989014秒
程序运行时间:20.885868310928345秒
程序运行时间:20.885868310928345秒
程序运行时间:20.885868310928345秒
程序运行时间:20.886868715286255秒
程序运行时间:20.886868715286255秒
程序运行时间:20.886868715286255秒
程序运行时间:20.887868881225586秒
程序运行时间:20.887868881225586秒
程序运行时间:20.888869047164917秒
程序运行时间:20.888869047164917秒
程序运行时间:20.888869047164917秒
程序运行时间:20.889869213104248秒
程序运行时间:20.89086937904358秒
程序运行时间:20.89086937904358秒
程序运行时间:20.89086937904358秒
程序运行时间:20.89186954498291秒
程序运行时间:20.89186954498291秒
程序运行时间:20.89286971092224秒
程序运行时间:20.89286971092224秒
程序运行时间:20.89286971092224秒
程序运行时间:20.893864154815674秒
程序运行时间:20.893864154815674秒
程序运行时间:20.89487051963806秒
程序运行时间:20.89487051963806秒
程序运行时间:20.89487051963806秒
程序运行时间:20.89587140083313秒
程序运行时间:20.89587140083313秒
程序运行时间:20.896870851516724秒
程序运行时间:20.896870851516724秒
程序运行时间:20.897871017456055秒
程序运行时间:20.897871017456055秒
程序运行时间:20.898871183395386秒
程序运行时间:20.898871183395386秒
程序运行时间:20.898871183395386秒
程序运行时间:20.899871826171875秒
程序运行时间:20.899871826171875秒
程序运行时间:20.900871753692627秒
程序运行时间:20.900871753692627秒
程序运行时间:20.901872158050537秒
程序运行时间:20.902872800827026秒
程序运行时间:20.9038724899292秒
程序运行时间:20.9038724899292秒
程序运行时间:20.9038724899292秒
程序运行时间:20.90487289428711秒
程序运行时间:20.90487289428711秒
程序运行时间:20.90587306022644秒
程序运行时间:20.90587306022644秒
程序运行时间:20.90587306022644秒
程序运行时间:20.906872987747192秒
程序运行时间:20.906872987747192秒
程序运行时间:20.906872987747192秒
程序运行时间:20.907873392105103秒
程序运行时间:20.907873392105103秒
程序运行时间:20.908873558044434秒
程序运行时间:20.908873558044434秒
程序运行时间:20.909873962402344秒
程序运行时间:20.909873962402344秒
程序运行时间:20.910874128341675秒
程序运行时间:20.911874294281006秒
程序运行时间:20.911874294281006秒
程序运行时间:20.912874698638916秒
程序运行时间:20.912874698638916秒
程序运行时间:20.913874626159668秒
程序运行时间:20.913874626159668秒
程序运行时间:20.914875030517578秒
程序运行时间:20.91587495803833秒
程序运行时间:20.91587495803833秒
程序运行时间:20.91587495803833秒
程序运行时间:20.91687536239624秒
程序运行时间:20.91687536239624秒
程序运行时间:20.91787576675415秒
程序运行时间:20.91787576675415秒
程序运行时间:20.91787576675415秒
程序运行时间:20.91887593269348秒
程序运行时间:20.919876098632812秒
程序运行时间:20.919876098632812秒
程序运行时间:20.919876098632812秒
程序运行时间:20.920876502990723秒
程序运行时间:20.920876502990723秒
程序运行时间:20.921876430511475秒
程序运行时间:20.921876430511475秒
程序运行时间:20.921876430511475秒
程序运行时间:20.922876834869385秒
程序运行时间:20.922876834869385秒
程序运行时间:20.922876834869385秒
程序运行时间:20.924877166748047秒
程序运行时间:20.924877166748047秒
程序运行时间:20.9258713722229秒
程序运行时间:20.9258713722229秒
程序运行时间:20.92687153816223秒
程序运行时间:20.92687153816223秒
程序运行时间:20.92788338661194秒
程序运行时间:20.92788338661194秒
程序运行时间:20.92888355255127秒
程序运行时间:20.92888355255127秒
程序运行时间:20.929877996444702秒
程序运行时间:20.929877996444702秒
程序运行时间:20.930878400802612秒
程序运行时间:20.930878400802612秒
程序运行时间:20.931878805160522秒
程序运行时间:20.931878805160522秒
程序运行时间:20.932884454727173秒
程序运行时间:20.932884454727173秒
程序运行时间:20.933879137039185秒
程序运行时间:20.933879137039185秒
程序运行时间:20.934879064559937秒
程序运行时间:20.934879064559937秒
程序运行时间:20.935879707336426秒
程序运行时间:20.935879707336426秒
程序运行时间:20.936885356903076秒
程序运行时间:20.936885356903076秒
程序运行时间:20.937885284423828秒
程序运行时间:20.93888020515442秒
程序运行时间:20.93888020515442秒
程序运行时间:20.93988037109375秒
程序运行时间:20.93988037109375秒
程序运行时间:20.94088053703308秒
程序运行时间:20.94088053703308秒
程序运行时间:20.94188642501831秒
程序运行时间:20.94188642501831秒
程序运行时间:20.94288659095764秒
程序运行时间:20.94288659095764秒
程序运行时间:20.943881511688232秒
程序运行时间:20.943881511688232秒
程序运行时间:20.944881677627563秒
程序运行时间:20.944881677627563秒
程序运行时间:20.945881605148315秒
程序运行时间:20.945881605148315秒
程序运行时间:20.946887254714966秒
程序运行时间:20.946887254714966秒
程序运行时间:20.947882175445557秒
程序运行时间:20.947882175445557秒
程序运行时间:20.948882579803467秒
程序运行时间:20.948882579803467秒
程序运行时间:20.949882745742798秒
程序运行时间:20.949882745742798秒
程序运行时间:20.95088291168213秒
程序运行时间:20.95088291168213秒
程序运行时间:20.95188879966736秒
程序运行时间:20.95188879966736秒
程序运行时间:20.95288896560669秒
程序运行时间:20.95288896560669秒
程序运行时间:20.9538836479187秒
程序运行时间:20.9538836479187秒
程序运行时间:20.954883813858032秒
程序运行时间:20.954883813858032秒
程序运行时间:20.955878019332886秒
程序运行时间:20.956889629364014秒
程序运行时间:20.957890033721924秒
程序运行时间:20.958884716033936秒
程序运行时间:20.958884716033936秒
程序运行时间:20.959890365600586秒
程序运行时间:20.959890365600586秒
程序运行时间:20.96088480949402秒
程序运行时间:20.96088480949402秒
程序运行时间:20.961885452270508秒
程序运行时间:20.961885452270508秒
程序运行时间:20.96288561820984秒
程序运行时间:20.96288561820984秒
程序运行时间:20.96389150619507秒
程序运行时间:20.96389150619507秒
程序运行时间:20.96489143371582秒
程序运行时间:20.965886116027832秒
程序运行时间:20.965886116027832秒
程序运行时间:20.966886520385742秒
程序运行时间:20.967892169952393秒
程序运行时间:20.967892169952393秒
程序运行时间:20.968892574310303秒
程序运行时间:20.968892574310303秒
程序运行时间:20.969892740249634秒
程序运行时间:20.97087526321411秒
程序运行时间:20.97087526321411秒
程序运行时间:20.9718816280365秒
程序运行时间:20.9718816280365秒
程序运行时间:20.97288179397583秒
程序运行时间:20.973893642425537秒
程序运行时间:20.974893808364868秒
程序运行时间:20.974893808364868秒
程序运行时间:20.9758939743042秒
程序运行时间:20.9758939743042秒
程序运行时间:20.97689414024353秒
程序运行时间:20.97689414024353秒
程序运行时间:20.97788906097412秒
程序运行时间:20.97788906097412秒
程序运行时间:20.978889226913452秒
程序运行时间:20.979889392852783秒
程序运行时间:20.980883598327637秒
程序运行时间:20.980883598327637秒
程序运行时间:20.981889724731445秒
程序运行时间:20.981889724731445秒
程序运行时间:20.982895612716675秒
程序运行时间:20.982895612716675秒
程序运行时间:20.983895778656006秒
程序运行时间:20.983895778656006秒
程序运行时间:20.984890460968018秒
程序运行时间:20.984890460968018秒
程序运行时间:20.985890865325928秒
程序运行时间:20.98689103126526秒
程序运行时间:20.98689103126526秒
程序运行时间:20.987885236740112秒
程序运行时间:20.988885402679443秒
程序运行时间:20.988885402679443秒
程序运行时间:20.989914655685425秒
程序运行时间:20.989914655685425秒
程序运行时间:20.99089217185974秒
程序运行时间:20.991886377334595秒
程序运行时间:20.991886377334595秒
程序运行时间:20.992886543273926秒
程序运行时间:20.993898153305054秒
程序运行时间:20.993898153305054秒
程序运行时间:20.994898319244385秒
程序运行时间:20.994898319244385秒
程序运行时间:20.995893001556396秒
程序运行时间:20.995893001556396秒
程序运行时间:20.996893167495728秒
程序运行时间:20.996893167495728秒
程序运行时间:20.997893571853638秒
程序运行时间:20.997893571853638秒
程序运行时间:20.99889373779297秒
程序运行时间:20.99889373779297秒
程序运行时间:20.9998939037323秒
程序运行时间:20.9998939037323秒
程序运行时间:21.00089406967163秒
程序运行时间:21.00089406967163秒
程序运行时间:21.00189971923828秒
程序运行时间:21.00189971923828秒
程序运行时间:21.002888679504395秒
程序运行时间:21.002888679504395秒
程序运行时间:21.003888845443726秒
程序运行时间:21.003888845443726秒
程序运行时间:21.004900455474854秒
程序运行时间:21.004900455474854秒
程序运行时间:21.005900621414185秒
程序运行时间:21.005900621414185秒
程序运行时间:21.006895542144775秒
程序运行时间:21.006895542144775秒
程序运行时间:21.007895708084106秒
程序运行时间:21.007895708084106秒
程序运行时间:21.008914470672607秒
程序运行时间:21.008914470672607秒
程序运行时间:21.00995373725891秒
程序运行时间:21.0108962059021秒
程序运行时间:21.0108962059021秒
程序运行时间:21.01189661026001秒
程序运行时间:21.01189661026001秒
程序运行时间:21.01290202140808秒
程序运行时间:21.01290202140808秒
程序运行时间:21.013896942138672秒
程序运行时间:21.013896942138672秒
程序运行时间:21.014897346496582秒
程序运行时间:21.014897346496582秒
程序运行时间:21.015897512435913秒
程序运行时间:21.015897512435913秒
程序运行时间:21.016903162002563秒
程序运行时间:21.016903162002563秒
程序运行时间:21.017897844314575秒
程序运行时间:21.017897844314575秒
程序运行时间:21.018898010253906秒
程序运行时间:21.018898010253906秒
程序运行时间:21.019903898239136秒
程序运行时间:21.019903898239136秒
程序运行时间:21.020898580551147秒
程序运行时间:21.020898580551147秒
程序运行时间:21.021898984909058秒
程序运行时间:21.021898984909058秒
程序运行时间:21.02289915084839秒
程序运行时间:21.02289915084839秒
程序运行时间:21.02389907836914秒
程序运行时间:21.02389907836914秒
程序运行时间:21.02489948272705秒
程序运行时间:21.02489948272705秒
程序运行时间:21.025899648666382秒
程序运行时间:21.025899648666382秒
程序运行时间:21.026899814605713秒
程序运行时间:21.026899814605713秒
程序运行时间:21.027899980545044秒
程序运行时间:21.027899980545044秒
程序运行时间:21.028900623321533秒
程序运行时间:21.028900623321533秒
程序运行时间:21.029905796051025秒
程序运行时间:21.029905796051025秒
程序运行时间:21.030900955200195秒
程序运行时间:21.030900955200195秒
程序运行时间:21.031901121139526秒
程序运行时间:21.031901121139526秒
程序运行时间:21.032901287078857秒
程序运行时间:21.032901287078857秒
程序运行时间:21.03390145301819秒
程序运行时间:21.03390145301819秒
程序运行时间:21.03489089012146秒
程序运行时间:21.035896062850952秒
程序运行时间:21.036896228790283秒
程序运行时间:21.036896228790283秒
程序运行时间:21.03790783882141秒
程序运行时间:21.03790783882141秒
程序运行时间:21.038908004760742秒
程序运行时间:21.038908004760742秒
程序运行时间:21.039902687072754秒
程序运行时间:21.039902687072754秒
程序运行时间:21.040903091430664秒
程序运行时间:21.040903091430664秒
程序运行时间:21.041903257369995秒
程序运行时间:21.041903257369995秒
程序运行时间:21.04291558265686秒
程序运行时间:21.04291558265686秒
程序运行时间:21.043917179107666秒
程序运行时间:21.043917179107666秒
程序运行时间:21.04490375518799秒
程序运行时间:21.04490375518799秒
程序运行时间:21.0459041595459秒
程序运行时间:21.04690980911255秒
程序运行时间:21.04690980911255秒
程序运行时间:21.0479097366333秒
程序运行时间:21.0479097366333秒
程序运行时间:21.04890489578247秒
程序运行时间:21.04890489578247秒
程序运行时间:21.0499050617218秒
程序运行时间:21.0499050617218秒
程序运行时间:21.050905227661133秒
程序运行时间:21.050905227661133秒
程序运行时间:21.051899909973145秒
程序运行时间:21.051899909973145秒
程序运行时间:21.052911281585693秒
程序运行时间:21.052911281585693秒
程序运行时间:21.053911685943604秒
程序运行时间:21.054906368255615秒
程序运行时间:21.054906368255615秒
程序运行时间:21.055906534194946秒
程序运行时间:21.055906534194946秒
程序运行时间:21.056911945343018秒
程序运行时间:21.056911945343018秒
程序运行时间:21.05790686607361秒
程序运行时间:21.05790686607361秒
程序运行时间:21.05890727043152秒
程序运行时间:21.05890727043152秒
程序运行时间:21.05991291999817秒
程序运行时间:21.05991291999817秒
程序运行时间:21.06090807914734秒
程序运行时间:21.06090807914734秒
程序运行时间:21.06190800666809秒
程序运行时间:21.06190800666809秒
程序运行时间:21.062913417816162秒
程序运行时间:21.062913417816162秒
程序运行时间:21.063908100128174秒
程序运行时间:21.063908100128174秒
程序运行时间:21.064908742904663秒
程序运行时间:21.064908742904663秒
程序运行时间:21.065908670425415秒
程序运行时间:21.065908670425415秒
程序运行时间:21.066908836364746秒
程序运行时间:21.066908836364746秒
程序运行时间:21.067903518676758秒
程序运行时间:21.067903518676758秒
程序运行时间:21.068909168243408秒
程序运行时间:21.068909168243408秒
程序运行时间:21.069915056228638秒
程序运行时间:21.069915056228638秒
程序运行时间:21.070915460586548秒
程序运行时间:21.070915460586548秒
程序运行时间:21.07191014289856秒
程序运行时间:21.07191014289856秒
程序运行时间:21.07291030883789秒
程序运行时间:21.07291030883789秒
程序运行时间:21.07391047477722秒
程序运行时间:21.07391047477722秒
程序运行时间:21.07491636276245秒
程序运行时间:21.07491636276245秒
程序运行时间:21.075916528701782秒
程序运行时间:21.075916528701782秒
程序运行时间:21.076911211013794秒
程序运行时间:21.077911138534546秒
程序运行时间:21.078917026519775秒
程序运行时间:21.079917192459106秒
程序运行时间:21.080912113189697秒
程序运行时间:21.080912113189697秒
程序运行时间:21.08191227912903秒

程序运行时间:21.32695460319519秒
程序运行时间:21.3319571018219秒
程序运行时间:21.33295726776123秒
程序运行时间:21.33295726776123秒
程序运行时间:21.333956003189087秒
程序运行时间:21.333956003189087秒
程序运行时间:21.334957361221313秒
程序运行时间:21.335958242416382秒
程序运行时间:21.336957931518555秒
程序运行时间:21.336957931518555秒
程序运行时间:21.337957859039307秒
程序运行时间:21.337957859039307秒
程序运行时间:21.33895707130432秒
程序运行时间:21.33895707130432秒
程序运行时间:21.339957237243652秒
程序运行时间:21.339957237243652秒
程序运行时间:21.340957403182983秒
程序运行时间:21.340957403182983秒
程序运行时间:21.34195828437805秒
程序运行时间:21.34195828437805秒
程序运行时间:21.34295892715454秒
程序运行时间:21.34295892715454秒
程序运行时间:21.34395956993103秒
程序运行时间:21.34395956993103秒
程序运行时间:21.34495973587036秒
程序运行时间:21.34596061706543秒
程序运行时间:21.34596061706543秒
程序运行时间:21.346960067749023秒
程序运行时间:21.347970724105835秒
程序运行时间:21.347970724105835秒
程序运行时间:21.348970890045166秒
程序运行时间:21.348970890045166秒
程序运行时间:21.34996747970581秒
程序运行时间:21.34996747970581秒
程序运行时间:21.34996747970581秒
程序运行时间:21.350966930389404秒
程序运行时间:21.350966930389404秒
程序运行时间:21.350966930389404秒
程序运行时间:21.351973056793213秒
程序运行时间:21.351973056793213秒
程序运行时间:21.352973222732544秒
程序运行时间:21.352973222732544秒
程序运行时间:21.352973222732544秒
程序运行时间:21.353973388671875秒
程序运行时间:21.354962825775146秒
程序运行时间:21.354962825775146秒
程序运行时间:21.35597515106201秒
程序运行时间:21.35597515106201秒
程序运行时间:21.356968879699707秒
程序运行时间:21.356968879699707秒
程序运行时间:21.356968879699707秒
程序运行时间:21.357961654663086秒
程序运行时间:21.357961654663086秒
程序运行时间:21.35896897315979秒
程序运行时间:21.35896897315979秒
程序运行时间:21.35997486114502秒
程序运行时间:21.35997486114502秒
程序运行时间:21.35997486114502秒
程序运行时间:21.36097502708435秒
程序运行时间:21.36097502708435秒
程序运行时间:21.36097502708435秒
程序运行时间:21.36197519302368秒
程序运行时间:21.362975120544434秒
程序运行时间:21.363975763320923秒
程序运行时间:21.363975763320923秒
程序运行时间:21.363975763320923秒
程序运行时间:21.364976167678833秒
程序运行时间:21.365976095199585秒
程序运行时间:21.365976095199585秒
程序运行时间:21.366976499557495秒
程序运行时间:21.366976499557495秒
程序运行时间:21.367976665496826秒
程序运行时间:21.367976665496826秒
程序运行时间:21.367976665496826秒
程序运行时间:21.368976831436157秒
程序运行时间:21.368976831436157秒
程序运行时间:21.369966745376587秒
程序运行时间:21.369966745376587秒
程序运行时间:21.37096619606018秒
程序运行时间:21.371966123580933秒
程序运行时间:21.372965574264526秒
程序运行时间:21.372965574264526秒
程序运行时间:21.373965978622437秒
程序运行时间:21.37496852874756秒
程序运行时间:21.37496852874756秒
程序运行时间:21.375967979431152秒
程序运行时间:21.375967979431152秒
程序运行时间:21.376967668533325秒
程序运行时间:21.376967668533325秒
程序运行时间:21.37797451019287秒
程序运行时间:21.37797451019287秒
程序运行时间:21.37897300720215秒
程序运行时间:21.379966735839844秒
程序运行时间:21.380967378616333秒
程序运行时间:21.381966590881348秒
程序运行时间:21.381966590881348秒
程序运行时间:21.382967233657837秒
程序运行时间:21.382967233657837秒
程序运行时间:21.38396716117859秒
程序运行时间:21.38396716117859秒
程序运行时间:21.38496732711792秒
程序运行时间:21.38596773147583秒
程序运行时间:21.38596773147583秒
程序运行时间:21.38696837425232秒
程序运行时间:21.38696837425232秒
程序运行时间:21.387969493865967秒
程序运行时间:21.389968395233154秒
程序运行时间:21.389968395233154秒
程序运行时间:21.390969038009644秒
程序运行时间:21.390969038009644秒
程序运行时间:21.391968965530396秒
程序运行时间:21.391968965530396秒
程序运行时间:21.392969131469727秒
程序运行时间:21.392969131469727秒
程序运行时间:21.393969297409058秒
程序运行时间:21.393969297409058秒
程序运行时间:21.39496946334839秒
程序运行时间:21.39496946334839秒
程序运行时间:21.395970344543457秒
程序运行时间:21.395970344543457秒
程序运行时间:21.3969783782959秒
程序运行时间:21.3969783782959秒
程序运行时间:21.397971630096436秒
程序运行时间:21.397971630096436秒
程序运行时间:21.397971630096436秒
程序运行时间:21.39898109436035秒
程序运行时间:21.39898109436035秒
程序运行时间:21.399978160858154秒
程序运行时间:21.399978160858154秒
程序运行时间:21.399978160858154秒
程序运行时间:21.400978326797485秒
程序运行时间:21.400978326797485秒
程序运行时间:21.401984214782715秒
程序运行时间:21.401984214782715秒
程序运行时间:21.401984214782715秒
程序运行时间:21.401984214782715秒
程序运行时间:21.403169631958008秒
程序运行时间:21.403169631958008秒
程序运行时间:21.403985023498535秒
程序运行时间:21.403985023498535秒
程序运行时间:21.404984951019287秒
程序运行时间:21.404984951019287秒
程序运行时间:21.404984951019287秒
程序运行时间:21.405980110168457秒
程序运行时间:21.405980110168457秒
程序运行时间:21.406985759735107秒
程序运行时间:21.406985759735107秒
程序运行时间:21.406985759735107秒
程序运行时间:21.40798568725586秒
程序运行时间:21.40798568725586秒
程序运行时间:21.40798568725586秒
程序运行时间:21.40898585319519秒
程序运行时间:21.40898585319519秒
程序运行时间:21.40998601913452秒
程序运行时间:21.40998601913452秒
程序运行时间:21.410974979400635秒
程序运行时间:21.410974979400635秒
程序运行时间:21.410974979400635秒
程序运行时间:21.411988019943237秒
程序运行时间:21.411988019943237秒
程序运行时间:21.411988019943237秒
程序运行时间:21.412980556488037秒
程序运行时间:21.412980556488037秒
程序运行时间:21.413981437683105秒
程序运行时间:21.413981437683105秒
程序运行时间:21.413981437683105秒
程序运行时间:21.414987564086914秒
程序运行时间:21.415987491607666秒
程序运行时间:21.415987491607666秒
程序运行时间:21.416987657546997秒
程序运行时间:21.416987657546997秒
程序运行时间:21.417988061904907秒
程序运行时间:21.417988061904907秒
程序运行时间:21.41898226737976秒
程序运行时间:21.41998815536499秒
程序运行时间:21.41998815536499秒
程序运行时间:21.41998815536499秒
程序运行时间:21.420982837677002秒
程序运行时间:21.420982837677002秒
程序运行时间:21.420982837677002秒
程序运行时间:21.42198872566223秒
程序运行时间:21.42198872566223秒
程序运行时间:21.422988414764404秒
程序运行时间:21.422988414764404秒
程序运行时间:21.422988414764404秒
程序运行时间:21.42398953437805秒
程序运行时间:21.42398953437805秒
程序运行时间:21.424989700317383秒
程序运行时间:21.424989700317383秒
程序运行时间:21.424989700317383秒
程序运行时间:21.425984144210815秒
程序运行时间:21.425984144210815秒
程序运行时间:21.425984144210815秒
程序运行时间:21.426989793777466秒
程序运行时间:21.426989793777466秒
程序运行时间:21.42798399925232秒
程序运行时间:21.42798399925232秒
程序运行时间:21.42798399925232秒
程序运行时间:21.42798399925232秒
程序运行时间:21.429258108139038秒
程序运行时间:21.429990530014038秒
程序运行时间:21.43099069595337秒
程序运行时间:21.43099069595337秒
程序运行时间:21.4319851398468秒
程序运行时间:21.4319851398468秒
程序运行时间:21.4319851398468秒
程序运行时间:21.43299126625061秒
程序运行时间:21.43299126625061秒
程序运行时间:21.43299126625061秒
程序运行时间:21.43399167060852秒
程序运行时间:21.43399167060852秒
程序运行时间:21.434991598129272秒
程序运行时间:21.434991598129272秒
程序运行时间:21.435991764068604秒
程序运行时间:21.435991764068604秒
程序运行时间:21.436986207962036秒
程序运行时间:21.436986207962036秒
程序运行时间:21.436986207962036秒
程序运行时间:21.437992334365845秒
程序运行时间:21.437992334365845秒
程序运行时间:21.437992334365845秒
程序运行时间:21.439189672470093秒
程序运行时间:21.439992427825928秒
程序运行时间:21.439992427825928秒
程序运行时间:21.439992427825928秒
程序运行时间:21.44099259376526秒
程序运行时间:21.44099259376526秒
程序运行时间:21.44198751449585秒
程序运行时间:21.44198751449585秒
程序运行时间:21.44198751449585秒
程序运行时间:21.442993640899658秒
程序运行时间:21.442993640899658秒
程序运行时间:21.442993640899658秒
程序运行时间:21.44399356842041秒
程序运行时间:21.44399356842041秒
程序运行时间:21.44499397277832秒
程序运行时间:21.44499397277832秒
程序运行时间:21.44499397277832秒
程序运行时间:21.445993900299072秒
程序运行时间:21.445993900299072秒
程序运行时间:21.446994304656982秒
程序运行时间:21.446994304656982秒
程序运行时间:21.446994304656982秒
程序运行时间:21.447994709014893秒
程序运行时间:21.447994709014893秒
程序运行时间:21.447994709014893秒
程序运行时间:21.448994636535645秒
程序运行时间:21.448994636535645秒
程序运行时间:21.449995040893555秒
程序运行时间:21.449995040893555秒
程序运行时间:21.449995040893555秒
程序运行时间:21.450995683670044秒
程序运行时间:21.450995683670044秒
程序运行时间:21.450995683670044秒
程序运行时间:21.451995611190796秒
程序运行时间:21.451995611190796秒
程序运行时间:21.452983856201172秒
程序运行时间:21.452983856201172秒
程序运行时间:21.452983856201172秒
程序运行时间:21.453995943069458秒
程序运行时间:21.453995943069458秒
程序运行时间:21.45499610900879秒
程序运行时间:21.45499610900879秒
程序运行时间:21.45499610900879秒
程序运行时间:21.45599603652954秒
程序运行时间:21.45599603652954秒
程序运行时间:21.45599603652954秒
程序运行时间:21.45699644088745秒
程序运行时间:21.45699644088745秒
程序运行时间:21.45799708366394秒
程序运行时间:21.45799708366394秒
程序运行时间:21.45899724960327秒
程序运行时间:21.459997415542603秒
程序运行时间:21.459997415542603秒
程序运行时间:21.459997415542603秒
程序运行时间:21.460997819900513秒
程序运行时间:21.460997819900513秒
程序运行时间:21.461997985839844秒
程序运行时间:21.461997985839844秒
程序运行时间:21.461997985839844秒
程序运行时间:21.462997913360596秒
程序运行时间:21.462997913360596秒
程序运行时间:21.462997913360596秒
程序运行时间:21.463998079299927秒
程序运行时间:21.464998245239258秒
程序运行时间:21.464998245239258秒
程序运行时间:21.464998245239258秒
程序运行时间:21.46599841117859秒
程序运行时间:21.4669988155365秒
程序运行时间:21.4669988155365秒
程序运行时间:21.4669988155365秒
程序运行时间:21.46799898147583秒
程序运行时间:21.46799898147583秒
程序运行时间:21.46799898147583秒
程序运行时间:21.46899914741516秒
程序运行时间:21.46899914741516秒
程序运行时间:21.46999955177307秒
程序运行时间:21.46999955177307秒
程序运行时间:21.46999955177307秒
程序运行时间:21.470999717712402秒
程序运行时间:21.470999717712402秒
程序运行时间:21.471999883651733秒
程序运行时间:21.471999883651733秒
程序运行时间:21.471999883651733秒
程序运行时间:21.473000049591064秒
程序运行时间:21.473000049591064秒
程序运行时间:21.473000049591064秒
程序运行时间:21.474000930786133秒
程序运行时间:21.474000930786133秒
程序运行时间:21.474995136260986秒
程序运行时间:21.474995136260986秒
程序运行时间:21.474995136260986秒
程序运行时间:21.47599506378174秒
程序运行时间:21.47599506378174秒
程序运行时间:21.477001190185547秒
程序运行时间:21.477001190185547秒
程序运行时间:21.477001190185547秒
程序运行时间:21.478001356124878秒
程序运行时间:21.478001356124878秒
程序运行时间:21.478001356124878秒
程序运行时间:21.47918963432312秒
程序运行时间:21.47918963432312秒
程序运行时间:21.48000168800354秒
程序运行时间:21.48000168800354秒
程序运行时间:21.48000168800354秒
程序运行时间:21.48100185394287秒
程序运行时间:21.48100185394287秒
程序运行时间:21.48100185394287秒
程序运行时间:21.48200225830078秒
程序运行时间:21.48200225830078秒
程序运行时间:21.48300266265869秒
程序运行时间:21.48300266265869秒
程序运行时间:21.48300266265869秒
程序运行时间:21.484002828598022秒
程序运行时间:21.484002828598022秒
程序运行时间:21.484002828598022秒
程序运行时间:21.485002756118774秒
程序运行时间:21.485002756118774秒
程序运行时间:21.486003160476685秒
程序运行时间:21.486003160476685秒
程序运行时间:21.487003326416016秒
程序运行时间:21.487003326416016秒
程序运行时间:21.488003730773926秒
程序运行时间:21.488003730773926秒
程序运行时间:21.488003730773926秒
程序运行时间:21.489003896713257秒
程序运行时间:21.489003896713257秒
程序运行时间:21.490004301071167秒
程序运行时间:21.490004301071167秒
程序运行时间:21.490004301071167秒
程序运行时间:21.49099826812744秒
程序运行时间:21.49099826812744秒
程序运行时间:21.49099826812744秒
程序运行时间:21.491998434066772秒
程序运行时间:21.491998434066772秒
程序运行时间:21.49300456047058秒
程序运行时间:21.49300456047058秒
程序运行时间:21.49300456047058秒
程序运行时间:21.49400496482849秒
程序运行时间:21.49400496482849秒
程序运行时间:21.49400496482849秒
程序运行时间:21.495005130767822秒
程序运行时间:21.495005130767822秒
程序运行时间:21.496005296707153秒
程序运行时间:21.496005296707153秒
程序运行时间:21.496005296707153秒
程序运行时间:21.497005462646484秒
程序运行时间:21.497005462646484秒
程序运行时间:21.498005867004395秒
程序运行时间:21.498005867004395秒
程序运行时间:21.498005867004395秒
程序运行时间:21.499006032943726秒
程序运行时间:21.499006032943726秒
程序运行时间:21.499006032943726秒
程序运行时间:21.500006437301636秒
程序运行时间:21.500006437301636秒
程序运行时间:21.501006603240967秒
程序运行时间:21.501006603240967秒
程序运行时间:21.501006603240967秒
程序运行时间:21.502006769180298秒
程序运行时间:21.502006769180298秒
程序运行时间:21.502006769180298秒
程序运行时间:21.50300669670105秒
程序运行时间:21.50300669670105秒
程序运行时间:21.50400710105896秒
程序运行时间:21.50400710105896秒
程序运行时间:21.50400710105896秒
程序运行时间:21.50500750541687秒
程序运行时间:21.50500750541687秒
程序运行时间:21.50599718093872秒
程序运行时间:21.50599718093872秒
程序运行时间:21.50599718093872秒
程序运行时间:21.507002115249634秒
程序运行时间:21.507002115249634秒
程序运行时间:21.508002281188965秒
程序运行时间:21.508002281188965秒
程序运行时间:21.508002281188965秒
程序运行时间:21.509008646011353秒
程序运行时间:21.509008646011353秒
程序运行时间:21.509008646011353秒
程序运行时间:21.510008573532104秒
程序运行时间:21.510008573532104秒
程序运行时间:21.511008501052856秒
程序运行时间:21.511008501052856秒
程序运行时间:21.511008501052856秒
程序运行时间:21.512008905410767秒
程序运行时间:21.512008905410767秒
程序运行时间:21.512008905410767秒
程序运行时间:21.51319718360901秒
程序运行时间:21.51319718360901秒
程序运行时间:21.514009475708008秒
程序运行时间:21.514009475708008秒
程序运行时间:21.514009475708008秒
程序运行时间:21.51500940322876秒
程序运行时间:21.51500940322876秒
程序运行时间:21.51500940322876秒
程序运行时间:21.51600956916809秒
程序运行时间:21.51600956916809秒
程序运行时间:21.517009973526秒
程序运行时间:21.517009973526秒
程序运行时间:21.517009973526秒
程序运行时间:21.51801037788391秒
程序运行时间:21.51801037788391秒
程序运行时间:21.51801037788391秒
程序运行时间:21.51901078224182秒
程序运行时间:21.51901078224182秒
程序运行时间:21.520010709762573秒
程序运行时间:21.520010709762573秒
程序运行时间:21.520010709762573秒
程序运行时间:21.521010875701904秒
程序运行时间:21.52199959754944秒
程序运行时间:21.523998975753784秒
程序运行时间:21.524998903274536秒
程序运行时间:21.525999069213867秒
程序运行时间:21.525999069213867秒
程序运行时间:21.526999473571777秒
程序运行时间:21.526999473571777秒
程序运行时间:21.52799940109253秒
程序运行时间:21.52799940109253秒
程序运行时间:21.52899980545044秒
程序运行时间:21.52899980545044秒
程序运行时间:21.52999997138977秒
程序运行时间:21.52999997138977秒
程序运行时间:21.5310001373291秒
程序运行时间:21.5310001373291秒
程序运行时间:21.532000303268433秒
程序运行时间:21.532000303268433秒
程序运行时间:21.533000707626343秒
程序运行时间:21.533000707626343秒
程序运行时间:21.534000873565674秒
程序运行时间:21.534000873565674秒
程序运行时间:21.535001039505005秒
程序运行时间:21.535001039505005秒
程序运行时间:21.536001205444336秒
程序运行时间:21.536001205444336秒
程序运行时间:21.537001609802246秒
程序运行时间:21.538002967834473秒
程序运行时间:21.539008855819702秒
程序运行时间:21.539008855819702秒
程序运行时间:21.54000949859619秒
程序运行时间:21.54000949859619秒
程序运行时间:21.541015625秒
程序运行时间:21.541015625秒
程序运行时间:21.541015625秒
程序运行时间:21.54201602935791秒
程序运行时间:21.54201602935791秒
程序运行时间:21.543015718460083秒
程序运行时间:21.543015718460083秒
程序运行时间:21.543015718460083秒
程序运行时间:21.544016122817993秒
程序运行时间:21.544016122817993秒
程序运行时间:21.545016288757324秒
程序运行时间:21.545016288757324秒
程序运行时间:21.546003580093384秒
程序运行时间:21.547012090682983秒
程序运行时间:21.54801082611084秒
程序运行时间:21.54801082611084秒
程序运行时间:21.54901123046875秒
程序运行时间:21.54901123046875秒
程序运行时间:21.55001735687256秒
程序运行时间:21.55001735687256秒
程序运行时间:21.55001735687256秒
程序运行时间:21.55101752281189秒
程序运行时间:21.55101752281189秒
程序运行时间:21.55101752281189秒
程序运行时间:21.55211305618286秒
程序运行时间:21.55211305618286秒
程序运行时间:21.55301809310913秒
程序运行时间:21.55301809310913秒
程序运行时间:21.55402183532715秒
程序运行时间:21.55402183532715秒
程序运行时间:21.55402183532715秒
程序运行时间:21.55501890182495秒
程序运行时间:21.55501890182495秒
程序运行时间:21.556018829345703秒
程序运行时间:21.556018829345703秒
程序运行时间:21.556018829345703秒
程序运行时间:21.557019233703613秒
程序运行时间:21.557019233703613秒
程序运行时间:21.557019233703613秒
程序运行时间:21.558019638061523秒
程序运行时间:21.558019638061523秒
程序运行时间:21.559019804000854秒
程序运行时间:21.559019804000854秒
程序运行时间:21.560019969940186秒
程序运行时间:21.561020135879517秒
程序运行时间:21.561020135879517秒
程序运行时间:21.561020135879517秒
程序运行时间:21.562020301818848秒
程序运行时间:21.562020301818848秒
程序运行时间:21.5630202293396秒
程序运行时间:21.5630202293396秒
程序运行时间:21.5630202293396秒
程序运行时间:21.56402063369751秒
程序运行时间:21.56402063369751秒
程序运行时间:21.56502056121826秒
程序运行时间:21.56502056121826秒
程序运行时间:21.56502056121826秒
程序运行时间:21.566020965576172秒
程序运行时间:21.567020893096924秒
程序运行时间:21.567020893096924秒
程序运行时间:21.567020893096924秒
程序运行时间:21.568021297454834秒
程序运行时间:21.568021297454834秒
程序运行时间:21.569021701812744秒
程序运行时间:21.569021701812744秒
程序运行时间:21.570015907287598秒
程序运行时间:21.570015907287598秒
程序运行时间:21.571016311645508秒
程序运行时间:21.571016311645508秒
程序运行时间:21.57201623916626秒
程序运行时间:21.57201623916626秒
程序运行时间:21.57301616668701秒
程序运行时间:21.57301616668701秒
程序运行时间:21.574024200439453秒
程序运行时间:21.575016975402832秒
程序运行时间:21.575016975402832秒
程序运行时间:21.576017141342163秒
程序运行时间:21.576017141342163秒
程序运行时间:21.57702350616455秒
程序运行时间:21.57702350616455秒
程序运行时间:21.578023672103882秒
程序运行时间:21.578023672103882秒
程序运行时间:21.579029083251953秒
程序运行时间:21.580012559890747秒
程序运行时间:21.580012559890747秒
程序运行时间:21.581019163131714秒
程序运行时间:21.581019163131714秒
程序运行时间:21.581019163131714秒

程序运行时间:21.583014965057373秒
程序运行时间:21.584012746810913秒
程序运行时间:21.584012746810913秒
程序运行时间:21.585012197494507秒
程序运行时间:21.585012197494507秒
程序运行时间:21.586012363433838秒
程序运行时间:21.586012363433838秒
程序运行时间:21.587012767791748秒
程序运行时间:21.587012767791748秒
程序运行时间:21.5880126953125秒
程序运行时间:21.5880126953125秒
程序运行时间:21.58901286125183秒
程序运行时间:21.58901286125183秒
程序运行时间:21.59001326560974秒
程序运行时间:21.59001326560974秒
程序运行时间:21.59101366996765秒
程序运行时间:21.59101366996765秒
程序运行时间:21.592013835906982秒
程序运行时间:21.592013835906982秒
程序运行时间:21.593014001846313秒
程序运行时间:21.593014001846313秒
程序运行时间:21.594014167785645秒
程序运行时间:21.595014572143555秒
程序运行时间:21.595014572143555秒
程序运行时间:21.596014499664307秒
程序运行时间:21.596014499664307秒
程序运行时间:21.597014904022217秒
程序运行时间:21.597014904022217秒
程序运行时间:21.598015069961548秒
程序运行时间:21.598015069961548秒
程序运行时间:21.599015474319458秒
程序运行时间:21.599015474319458秒
程序运行时间:21.600016117095947秒
程序运行时间:21.600016117095947秒
程序运行时间:21.60101628303528秒
程序运行时间:21.60101628303528秒
程序运行时间:21.60201597213745秒
程序运行时间:21.60201597213745秒
程序运行时间:21.60301661491394秒
程序运行时间:21.60301661491394秒
程序运行时间:21.604016542434692秒
程序运行时间:21.604016542434692秒
程序运行时间:21.605016708374023秒
程序运行时间:21.605016708374023秒
程序运行时间:21.606016874313354秒
程序运行时间:21.60701847076416秒
程序运行时间:21.60701847076416秒
程序运行时间:21.608017444610596秒
程序运行时间:21.609017610549927秒
程序运行时间:21.609017610549927秒
程序运行时间:21.610017776489258秒
程序运行时间:21.610017776489258秒
程序运行时间:21.61101794242859秒
程序运行时间:21.61101794242859秒
程序运行时间:21.61201810836792秒
程序运行时间:21.61201810836792秒
程序运行时间:21.61301827430725秒
程序运行时间:21.61301827430725秒
程序运行时间:21.61401867866516秒
程序运行时间:21.61401867866516秒
程序运行时间:21.615018844604492秒
程序运行时间:21.616020679473877秒
程序运行时间:21.616020679473877秒
程序运行时间:21.61702275276184秒
程序运行时间:21.61702275276184秒
程序运行时间:21.61802101135254秒
程序运行时间:21.61802101135254秒
程序运行时间:21.619019985198975秒
程序运行时间:21.619019985198975秒
程序运行时间:21.620020151138306秒
程序运行时间:21.620020151138306秒
程序运行时间:21.621020317077637秒
程序运行时间:21.621020317077637秒
程序运行时间:21.622020483016968秒
程序运行时间:21.622020483016968秒
程序运行时间:21.6230206489563秒
程序运行时间:21.6230206489563秒
程序运行时间:21.62402081489563秒
程序运行时间:21.625023126602173秒
程序运行时间:21.625023126602173秒
程序运行时间:21.626023054122925秒
程序运行时间:21.627026081085205秒
程序运行时间:21.627026081085205秒
程序运行时间:21.628021955490112秒
程序运行时间:21.628021955490112秒
程序运行时间:21.629022121429443秒
程序运行时间:21.629022121429443秒
程序运行时间:21.630022525787354秒
程序运行时间:21.630022525787354秒
程序运行时间:21.631022453308105秒
程序运行时间:21.63202404975891秒
程序运行时间:21.63302993774414秒
程序运行时间:21.63302993774414秒
程序运行时间:21.634042024612427秒
程序运行时间:21.634042024612427秒
程序运行时间:21.63503646850586秒
程序运行时间:21.63503646850586秒
程序运行时间:21.63503646850586秒
程序运行时间:21.636319398880005秒
程序运行时间:21.636319398880005秒
程序运行时间:21.63703751564026秒
程序运行时间:21.63703751564026秒
程序运行时间:21.63803768157959秒
程序运行时间:21.63803768157959秒
程序运行时间:21.63803768157959秒
程序运行时间:21.639037609100342秒
程序运行时间:21.639037609100342秒
程序运行时间:21.640037536621094秒
程序运行时间:21.640037536621094秒
程序运行时间:21.640037536621094秒
程序运行时间:21.641037702560425秒
程序运行时间:21.641037702560425秒
程序运行时间:21.642038345336914秒
程序运行时间:21.642038345336914秒
程序运行时间:21.642038345336914秒
程序运行时间:21.643038511276245秒
程序运行时间:21.6440532207489秒
程序运行时间:21.6440532207489秒
程序运行时间:21.6440532207489秒
程序运行时间:21.645038843154907秒
程序运行时间:21.645038843154907秒
程序运行时间:21.64603877067566秒
程序运行时间:21.64703917503357秒
程序运行时间:21.6480393409729秒
程序运行时间:21.6480393409729秒
程序运行时间:21.64903950691223秒
程序运行时间:21.650045156478882秒
程序运行时间:21.650045156478882秒
程序运行时间:21.651180267333984秒
程序运行时间:21.652045726776123秒
程序运行时间:21.65335512161255秒
程序运行时间:21.654048204421997秒
程序运行时间:21.6550350189209秒
程序运行时间:21.6550350189209秒
程序运行时间:21.65603518486023秒
程序运行时间:21.657047033309937秒
程序运行时间:21.65804147720337秒
程序运行时间:21.6590473651886秒
程序运行时间:21.6590473651886秒
程序运行时间:21.66004753112793秒
程序运行时间:21.66004753112793秒
程序运行时间:21.66104221343994秒
程序运行时间:21.663036823272705秒
程序运行时间:21.663036823272705秒
程序运行时间:21.664037466049194秒
程序运行时间:21.664037466049194秒
程序运行时间:21.665043592453003秒
程序运行时间:21.665043592453003秒
程序运行时间:21.666043281555176秒
程序运行时间:21.666043281555176秒
程序运行时间:21.667049646377563秒
程序运行时间:21.667049646377563秒
程序运行时间:21.668039321899414秒
程序运行时间:21.668039321899414秒
程序运行时间:21.66903805732727秒
程序运行时间:21.66903805732727秒
程序运行时间:21.66903805732727秒
程序运行时间:21.67003870010376秒
程序运行时间:21.67003870010376秒
程序运行时间:21.67104458808899秒
程序运行时间:21.67104458808899秒
程序运行时间:21.67104458808899秒
程序运行时间:21.67204451560974秒
程序运行时间:21.67204451560974秒
程序运行时间:21.67204451560974秒
程序运行时间:21.6732337474823秒
程序运行时间:21.6732337474823秒
程序运行时间:21.67404532432556秒
程序运行时间:21.67404532432556秒
程序运行时间:21.67404532432556秒
程序运行时间:21.67505955696106秒
程序运行时间:21.67505955696106秒
程序运行时间:21.676045417785645秒
程序运行时间:21.676045417785645秒
程序运行时间:21.676045417785645秒
程序运行时间:21.67803454399109秒
程序运行时间:21.679033279418945秒
程序运行时间:21.679033279418945秒
程序运行时间:21.680033445358276秒
程序运行时间:21.680033445358276秒
程序运行时间:21.681033611297607秒
程序运行时间:21.681033611297607秒
程序运行时间:21.682034254074097秒
程序运行时间:21.682034254074097秒
程序运行时间:21.683034420013428秒
程序运行时间:21.683034420013428秒
程序运行时间:21.684034824371338秒
程序运行时间:21.684034824371338秒
程序运行时间:21.68503451347351秒
程序运行时间:21.68503451347351秒
程序运行时间:21.68603491783142秒
程序运行时间:21.68703532218933秒
程序运行时间:21.68703532218933秒
程序运行时间:21.688035249710083秒
程序运行时间:21.688035249710083秒
程序运行时间:21.689035415649414秒
程序运行时间:21.689035415649414秒
程序运行时间:21.690035820007324秒
程序运行时间:21.690035820007324秒
程序运行时间:21.691035747528076秒
程序运行时间:21.691035747528076秒
程序运行时间:21.692035913467407秒
程序运行时间:21.692035913467407秒
程序运行时间:21.693036556243896秒
程序运行时间:21.693036556243896秒
程序运行时间:21.694036960601807秒
程序运行时间:21.694036960601807秒
程序运行时间:21.69503688812256秒
程序运行时间:21.69603729248047秒
程序运行时间:21.69603729248047秒
程序运行时间:21.69703769683838秒
程序运行时间:21.69703769683838秒
程序运行时间:21.69803738594055秒
程序运行时间:21.69803738594055秒
程序运行时间:21.699037551879883秒
程序运行时间:21.70003843307495秒
程序运行时间:21.701038360595703秒
程序运行时间:21.702038526535034秒
程序运行时间:21.702038526535034秒
程序运行时间:21.703038692474365秒
程序运行时间:21.704039096832275秒
程序运行时间:21.705039024353027秒
程序运行时间:21.705039024353027秒
程序运行时间:21.70703959465027秒
程序运行时间:21.70703959465027秒
程序运行时间:21.7080397605896秒
程序运行时间:21.7080397605896秒
程序运行时间:21.70904040336609秒
程序运行时间:21.70904040336609秒
程序运行时间:21.71004033088684秒
程序运行时间:21.71004033088684秒
程序运行时间:21.711040496826172秒
程序运行时间:21.711040496826172秒
程序运行时间:21.712040662765503秒
程序运行时间:21.712040662765503秒
程序运行时间:21.713040828704834秒
程序运行时间:21.713040828704834秒
程序运行时间:21.714041709899902秒
程序运行时间:21.714041709899902秒
程序运行时间:21.715041399002075秒
程序运行时间:21.715041399002075秒
程序运行时间:21.716041564941406秒
程序运行时间:21.716041564941406秒
程序运行时间:21.717042207717896秒
程序运行时间:21.717042207717896秒
程序运行时间:21.718042135238647秒
程序运行时间:21.718042135238647秒
程序运行时间:21.71904230117798秒
程序运行时间:21.71904230117798秒
程序运行时间:21.72004246711731秒
程序运行时间:21.72004246711731秒
程序运行时间:21.72104263305664秒
程序运行时间:21.72104263305664秒
程序运行时间:21.72204303741455秒
程序运行时间:21.72204303741455秒
程序运行时间:21.723043203353882秒
程序运行时间:21.724043369293213秒
程序运行时间:21.724043369293213秒
程序运行时间:21.725043535232544秒
程序运行时间:21.72604537010193秒
程序运行时间:21.72604537010193秒
程序运行时间:21.727044343948364秒
程序运行时间:21.727044343948364秒
程序运行时间:21.728044271469116秒
程序运行时间:21.728044271469116秒
程序运行时间:21.729044675827026秒
程序运行时间:21.729044675827026秒
程序运行时间:21.730045080184937秒
程序运行时间:21.730045080184937秒
程序运行时间:21.73104500770569秒
程序运行时间:21.73104500770569秒
程序运行时间:21.73204517364502秒
程序运行时间:21.73204517364502秒
程序运行时间:21.73304533958435秒
程序运行时间:21.73304533958435秒
程序运行时间:21.73404574394226秒
程序运行时间:21.73404574394226秒
程序运行时间:21.735045909881592秒
程序运行时间:21.735045909881592秒
程序运行时间:21.736046075820923秒
程序运行时间:21.736046075820923秒
程序运行时间:21.737046241760254秒
程序运行时间:21.737046241760254秒
程序运行时间:21.738046646118164秒
程序运行时间:21.738046646118164秒
程序运行时间:21.739046812057495秒
程序运行时间:21.739046812057495秒
程序运行时间:21.740046977996826秒
程序运行时间:21.74104928970337秒
程序运行时间:21.742047786712646秒
程序运行时间:21.742047786712646秒
程序运行时间:21.743048667907715秒
程序运行时间:21.744048833847046秒
程序运行时间:21.744048833847046秒
程序运行时间:21.74504828453064秒
程序运行时间:21.74504828453064秒
程序运行时间:21.74604821205139秒
程序运行时间:21.74604821205139秒
程序运行时间:21.7470486164093秒
程序运行时间:21.7470486164093秒
程序运行时间:21.748048782348633秒
程序运行时间:21.748048782348633秒
程序运行时间:21.749048948287964秒
程序运行时间:21.749048948287964秒
程序运行时间:21.750049352645874秒
程序运行时间:21.750049352645874秒
程序运行时间:21.751049757003784秒
程序运行时间:21.751049757003784秒
程序运行时间:21.752049684524536秒
程序运行时间:21.752049684524536秒
程序运行时间:21.753049850463867秒
程序运行时间:21.753049850463867秒
程序运行时间:21.754050731658936秒
程序运行时间:21.754050731658936秒
程序运行时间:21.75505042076111秒
程序运行时间:21.75505042076111秒
程序运行时间:21.757051944732666秒
程序运行时间:21.757051944732666秒
程序运行时间:21.7580509185791秒
程序运行时间:21.75905156135559秒
程序运行时间:21.75905156135559秒
程序运行时间:21.760051727294922秒
程序运行时间:21.760051727294922秒
程序运行时间:21.761051893234253秒
程序运行时间:21.761051893234253秒
程序运行时间:21.762052059173584秒
程序运行时间:21.762052059173584秒
程序运行时间:21.763052463531494秒
程序运行时间:21.764052391052246秒
程序运行时间:21.764052391052246秒
程序运行时间:21.765052556991577秒
程序运行时间:21.765052556991577秒
程序运行时间:21.76705265045166秒
程序运行时间:21.76705265045166秒
程序运行时间:21.76805329322815秒
程序运行时间:21.76805329322815秒
程序运行时间:21.76905345916748秒
程序运行时间:21.76905345916748秒
程序运行时间:21.77005434036255秒
程序运行时间:21.77005434036255秒
程序运行时间:21.7710542678833秒
程序运行时间:21.7710542678833秒
程序运行时间:21.772054195404053秒
程序运行时间:21.773054838180542秒
程序运行时间:21.773054838180542秒
程序运行时间:21.774054765701294秒
程序运行时间:21.774054765701294秒
程序运行时间:21.775054931640625秒
程序运行时间:21.775054931640625秒
程序运行时间:21.776054859161377秒
程序运行时间:21.776054859161377秒
程序运行时间:21.777055263519287秒
程序运行时间:21.777055263519287秒
程序运行时间:21.778055667877197秒
程序运行时间:21.778055667877197秒
程序运行时间:21.779056072235107秒
程序运行时间:21.779056072235107秒
程序运行时间:21.78005599975586秒
程序运行时间:21.78005599975586秒
程序运行时间:21.78105616569519秒
程序运行时间:21.78105616569519秒
程序运行时间:21.78205633163452秒
程序运行时间:21.78205633163452秒
程序运行时间:21.783056497573853秒
程序运行时间:21.783056497573853秒
程序运行时间:21.784056663513184秒
程序运行时间:21.784056663513184秒
程序运行时间:21.785057306289673秒
程序运行时间:21.785057306289673秒
程序运行时间:21.786057233810425秒
程序运行时间:21.786057233810425秒
程序运行时间:21.787057638168335秒
程序运行时间:21.787057638168335秒
程序运行时间:21.788058042526245秒
程序运行时间:21.788058042526245秒
程序运行时间:21.789058208465576秒
程序运行时间:21.789058208465576秒
程序运行时间:21.790058374404907秒
程序运行时间:21.790058374404907秒
程序运行时间:21.79105830192566秒
程序运行时间:21.79105830192566秒
程序运行时间:21.79205870628357秒
程序运行时间:21.79205870628357秒
程序运行时间:21.79305911064148秒
程序运行时间:21.79305911064148秒
程序运行时间:21.79405903816223秒
程序运行时间:21.79405903816223秒
程序运行时间:21.79505968093872秒
程序运行时间:21.79505968093872秒
程序运行时间:21.796059608459473秒
程序运行时间:21.796059608459473秒
程序运行时间:21.797060012817383秒
程序运行时间:21.797060012817383秒
程序运行时间:21.798059940338135秒
程序运行时间:21.798059940338135秒
程序运行时间:21.799060106277466秒
程序运行时间:21.799060106277466秒
程序运行时间:21.800060272216797秒
程序运行时间:21.800060272216797秒
程序运行时间:21.801060438156128秒
程序运行时间:21.801060438156128秒
程序运行时间:21.802061319351196秒
程序运行时间:21.802061319351196秒
程序运行时间:21.80306124687195秒
程序运行时间:21.804062843322754秒
程序运行时间:21.80506157875061秒
程序运行时间:21.80506157875061秒
程序运行时间:21.80506157875061秒
程序运行时间:21.80606174468994秒
程序运行时间:21.80606174468994秒
程序运行时间:21.80606174468994秒
程序运行时间:21.80706262588501秒
程序运行时间:21.80706262588501秒
程序运行时间:21.80806303024292秒
程序运行时间:21.80806303024292秒
程序运行时间:21.80806303024292秒
程序运行时间:21.80906319618225秒
程序运行时间:21.80906319618225秒
程序运行时间:21.80906319618225秒
程序运行时间:21.810063362121582秒
程序运行时间:21.810063362121582秒
程序运行时间:21.811063528060913秒
程序运行时间:21.811063528060913秒
程序运行时间:21.811063528060913秒
程序运行时间:21.812063694000244秒
程序运行时间:21.812063694000244秒
程序运行时间:21.812063694000244秒
程序运行时间:21.813063621520996秒
程序运行时间:21.813063621520996秒
程序运行时间:21.81406569480896秒
程序运行时间:21.81406569480896秒
程序运行时间:21.81406569480896秒
程序运行时间:21.81506371498108秒
程序运行时间:21.81506371498108秒
程序运行时间:21.81506371498108秒
程序运行时间:21.81606388092041秒
程序运行时间:21.81606388092041秒
程序运行时间:21.817065000534058秒
程序运行时间:21.817065000534058秒
程序运行时间:21.817065000534058秒
程序运行时间:21.818065404891968秒
程序运行时间:21.819066524505615秒
程序运行时间:21.819066524505615秒
程序运行时间:21.82006549835205秒
程序运行时间:21.82006549835205秒
程序运行时间:21.82006549835205秒
程序运行时间:21.821065187454224秒
程序运行时间:21.821065187454224秒
程序运行时间:21.822065830230713秒
程序运行时间:21.822065830230713秒
程序运行时间:21.822065830230713秒
程序运行时间:21.823066234588623秒
程序运行时间:21.823066234588623秒
程序运行时间:21.824066400527954秒
程序运行时间:21.824066400527954秒
程序运行时间:21.825066804885864秒
程序运行时间:21.825066804885864秒
程序运行时间:21.825066804885864秒
程序运行时间:21.826066970825195秒
程序运行时间:21.826066970825195秒
程序运行时间:21.826066970825195秒
程序运行时间:21.827067136764526秒
程序运行时间:21.827067136764526秒
程序运行时间:21.828067302703857秒
程序运行时间:21.828067302703857秒
程序运行时间:21.829067707061768秒
程序运行时间:21.8300678730011秒
程序运行时间:21.8300678730011秒
程序运行时间:21.8300678730011秒
程序运行时间:21.83106803894043秒
程序运行时间:21.83106803894043秒
程序运行时间:21.83106803894043秒
程序运行时间:21.83206820487976秒
程序运行时间:21.83206820487976秒
程序运行时间:21.833068370819092秒
程序运行时间:21.833068370819092秒
程序运行时间:21.833068370819092秒
程序运行时间:21.83406925201416秒
程序运行时间:21.83406925201416秒
程序运行时间:21.83506989479065秒
程序运行时间:21.83506989479065秒
程序运行时间:21.83506989479065秒
程序运行时间:21.836069345474243秒
程序运行时间:21.836069345474243秒
程序运行时间:21.836069345474243秒
程序运行时间:21.837068796157837秒
程序运行时间:21.837068796157837秒
程序运行时间:21.838069915771484秒
程序运行时间:21.838069915771484秒
程序运行时间:21.838069915771484秒
程序运行时间:21.839070081710815秒
程序运行时间:21.839070081710815秒
程序运行时间:21.839070081710815秒
程序运行时间:21.840070247650146秒
程序运行时间:21.840070247650146秒
程序运行时间:21.841070413589478秒
程序运行时间:21.841070413589478秒
程序运行时间:21.842070817947388秒
程序运行时间:21.842070817947388秒
程序运行时间:21.84307050704956秒
程序运行时间:21.84307050704956秒
程序运行时间:21.844072580337524秒
程序运行时间:21.844072580337524秒
程序运行时间:21.84507131576538秒
程序运行时间:21.84507131576538秒
程序运行时间:21.84507131576538秒
程序运行时间:21.846070766448975秒
程序运行时间:21.846070766448975秒
程序运行时间:21.846070766448975秒
程序运行时间:21.847071886062622秒
程序运行时间:21.847071886062622秒
程序运行时间:21.848071813583374秒
程序运行时间:21.848071813583374秒
程序运行时间:21.848071813583374秒
程序运行时间:21.849071979522705秒
程序运行时间:21.850072145462036秒
程序运行时间:21.850072145462036秒
程序运行时间:21.851073741912842秒
程序运行时间:21.852072715759277秒
程序运行时间:21.85307264328003秒
程序运行时间:21.85407328605652秒
程序运行时间:21.85508704185486秒
程序运行时间:21.85508704185486秒
程序运行时间:21.856086492538452秒
程序运行时间:21.857086420059204秒
程序运行时间:21.858086585998535秒
程序运行时间:21.859086513519287秒
程序运行时间:21.859086513519287秒
程序运行时间:21.859086513519287秒
程序运行时间:21.860086917877197秒
程序运行时间:21.86108708381653秒
程序运行时间:21.86108708381653秒
程序运行时间:21.86108708381653秒
程序运行时间:21.86208724975586秒
程序运行时间:21.86208724975586秒
程序运行时间:21.86208724975586秒
程序运行时间:21.863340854644775秒
程序运行时间:21.86408829689026秒
程序运行时间:21.86508822441101秒
程序运行时间:21.86508822441101秒
程序运行时间:21.86508822441101秒
程序运行时间:21.86608862876892秒
程序运行时间:21.86608862876892秒
程序运行时间:21.86608862876892秒
程序运行时间:21.867088794708252秒
程序运行时间:21.867088794708252秒
程序运行时间:21.868088722229004秒
程序运行时间:21.868088722229004秒
程序运行时间:21.868088722229004秒
程序运行时间:21.869083404541016秒
程序运行时间:21.869083404541016秒
程序运行时间:21.869083404541016秒
程序运行时间:21.870089054107666秒
程序运行时间:21.870089054107666秒
程序运行时间:21.871089458465576秒
程序运行时间:21.871089458465576秒
程序运行时间:21.871089458465576秒
程序运行时间:21.872089624404907秒
程序运行时间:21.873090028762817秒
程序运行时间:21.873090028762817秒
程序运行时间:21.874090433120728秒
程序运行时间:21.874090433120728秒
程序运行时间:21.87509036064148秒
程序运行时间:21.87509036064148秒
程序运行时间:21.87509036064148秒
程序运行时间:21.87609052658081秒
程序运行时间:21.87609052658081秒
程序运行时间:21.87609052658081秒
程序运行时间:21.87709069252014秒
程序运行时间:21.87709069252014秒
程序运行时间:21.878090858459473秒
程序运行时间:21.878090858459473秒
程序运行时间:21.87909197807312秒
程序运行时间:21.87909197807312秒
程序运行时间:21.880091905593872秒
程序运行时间:21.880091905593872秒
程序运行时间:21.880091905593872秒
程序运行时间:21.881091594696045秒
程序运行时间:21.881091594696045秒
程序运行时间:21.881091594696045秒
程序运行时间:21.882092237472534秒
程序运行时间:21.882092237472534秒
程序运行时间:21.883092403411865秒
程序运行时间:21.883092403411865秒
程序运行时间:21.884092569351196秒
程序运行时间:21.885092735290527秒
程序运行时间:21.885092735290527秒
程序运行时间:21.885092735290527秒
程序运行时间:21.88609290122986秒
程序运行时间:21.88709306716919秒
程序运行时间:21.88709306716919秒
程序运行时间:21.88709306716919秒
程序运行时间:21.8880934715271秒
程序运行时间:21.8880934715271秒
程序运行时间:21.8880934715271秒
程序运行时间:21.88909339904785秒
程序运行时间:21.88909339904785秒
程序运行时间:21.89009404182434秒
程序运行时间:21.89009404182434秒
程序运行时间:21.891094207763672秒
程序运行时间:21.891094207763672秒
程序运行时间:21.892094135284424秒
程序运行时间:21.892094135284424秒
程序运行时间:21.892094135284424秒
程序运行时间:21.893094539642334秒
程序运行时间:21.893094539642334秒
程序运行时间:21.893094539642334秒
程序运行时间:21.894094944000244秒
程序运行时间:21.894094944000244秒
程序运行时间:21.895094871520996秒
程序运行时间:21.895094871520996秒
程序运行时间:21.895094871520996秒
程序运行时间:21.896095275878906秒
程序运行时间:21.896095275878906秒
程序运行时间:21.897083520889282秒
程序运行时间:21.898095846176147秒
程序运行时间:21.8990957736969秒
程序运行时间:21.8990957736969秒
程序运行时间:21.90009617805481秒
程序运行时间:21.90109658241272秒
程序运行时间:21.90109658241272秒
程序运行时间:21.90109658241272秒
程序运行时间:21.90209674835205秒
程序运行时间:21.90209674835205秒
程序运行时间:21.90209674835205秒
程序运行时间:21.903096199035645秒
程序运行时间:21.903096199035645秒
程序运行时间:21.904096603393555秒
程序运行时间:21.904096603393555秒
程序运行时间:21.904096603393555秒
程序运行时间:21.905097246170044秒
程序运行时间:21.905097246170044秒
程序运行时间:21.905097246170044秒
程序运行时间:21.906097412109375秒
程序运行时间:21.906097412109375秒
程序运行时间:21.907097578048706秒
程序运行时间:21.907097578048706秒
程序运行时间:21.907097578048706秒
程序运行时间:21.908097743988037秒
程序运行时间:21.908097743988037秒
程序运行时间:21.909098625183105秒
程序运行时间:21.909098625183105秒
程序运行时间:21.909098625183105秒
程序运行时间:21.91009831428528秒
程序运行时间:21.91009831428528秒
程序运行时间:21.91009831428528秒
程序运行时间:21.91109848022461秒
程序运行时间:21.91109848022461秒
程序运行时间:21.91209840774536秒
程序运行时间:21.91209840774536秒
程序运行时间:21.91209840774536秒
程序运行时间:21.913086414337158秒
程序运行时间:21.913086414337158秒
程序运行时间:21.913086414337158秒
程序运行时间:21.91409945487976秒
程序运行时间:21.91409945487976秒
程序运行时间:21.915218591690063秒
程序运行时间:21.915218591690063秒
程序运行时间:21.91609501838684秒
程序运行时间:21.91710090637207秒
程序运行时间:21.91710090637207秒
程序运行时间:21.91710090637207秒
程序运行时间:21.918094873428345秒
程序运行时间:21.918094873428345秒
程序运行时间:21.918094873428345秒
程序运行时间:21.919100284576416秒
程序运行时间:21.919100284576416秒
程序运行时间:21.920100212097168秒
程序运行时间:21.920100212097168秒
程序运行时间:21.920100212097168秒
程序运行时间:21.921100616455078秒
程序运行时间:21.921100616455078秒
程序运行时间:21.921100616455078秒
程序运行时间:21.92210102081299秒
程序运行时间:21.92210102081299秒
程序运行时间:21.92310118675232秒
程序运行时间:21.92310118675232秒
程序运行时间:21.92410159111023秒
程序运行时间:21.92410159111023秒
程序运行时间:21.925101280212402秒
程序运行时间:21.925101280212402秒
程序运行时间:21.925101280212402秒
程序运行时间:21.926101684570312秒
程序运行时间:21.926101684570312秒
程序运行时间:21.926101684570312秒
程序运行时间:21.927101850509644秒
程序运行时间:21.927101850509644秒
程序运行时间:21.928102493286133秒
程序运行时间:21.928102493286133秒
程序运行时间:21.928102493286133秒
程序运行时间:21.929089546203613秒
程序运行时间:21.929089546203613秒
程序运行时间:21.930103302001953秒
程序运行时间:21.930103302001953秒
程序运行时间:21.930103302001953秒
程序运行时间:21.931196928024292秒
程序运行时间:21.93209218978882秒
程序运行时间:21.93309187889099秒
程序运行时间:21.93409037590027秒
程序运行时间:21.935098886489868秒
程序运行时间:21.935098886489868秒
程序运行时间:21.93609881401062秒
程序运行时间:21.93609881401062秒
程序运行时间:21.937098741531372秒
程序运行时间:21.937098741531372秒
程序运行时间:21.937098741531372秒
程序运行时间:21.93810486793518秒
程序运行时间:21.93810486793518秒
程序运行时间:21.93910503387451秒
程序运行时间:21.93910503387451秒
程序运行时间:21.93910503387451秒
程序运行时间:21.940104961395264秒
程序运行时间:21.940104961395264秒
程序运行时间:21.940104961395264秒
程序运行时间:21.941105365753174秒
程序运行时间:21.941105365753174秒
程序运行时间:21.942105531692505秒
程序运行时间:21.942105531692505秒
程序运行时间:21.942105531692505秒
程序运行时间:21.943105697631836秒
程序运行时间:21.943105697631836秒
程序运行时间:21.944105863571167秒
程序运行时间:21.945093631744385秒
程序运行时间:21.945093631744385秒
程序运行时间:21.946094036102295秒
程序运行时间:21.94709348678589秒
程序运行时间:21.94709348678589秒
程序运行时间:21.94809365272522秒
程序运行时间:21.94809365272522秒
程序运行时间:21.94909381866455秒
程序运行时间:21.94909381866455秒
程序运行时间:21.950093984603882秒
程序运行时间:21.950093984603882秒
程序运行时间:21.951094388961792秒
程序运行时间:21.951094388961792秒
程序运行时间:21.952094793319702秒
程序运行时间:21.952094793319702秒
程序运行时间:21.953094959259033秒
程序运行时间:21.953094959259033秒
程序运行时间:21.954095363616943秒
程序运行时间:21.954095363616943秒
程序运行时间:21.955095529556274秒
程序运行时间:21.955095529556274秒
程序运行时间:21.956095457077026秒
程序运行时间:21.956095457077026秒
程序运行时间:21.957095623016357秒
程序运行时间:21.957095623016357秒
程序运行时间:21.958096027374268秒
程序运行时间:21.958096027374268秒
程序运行时间:21.95909595489502秒
程序运行时间:21.95909595489502秒
程序运行时间:21.96009635925293秒

程序运行时间:22.28819751739502秒
程序运行时间:22.29019784927368秒
程序运行时间:22.29019784927368秒
程序运行时间:22.29119873046875秒
程序运行时间:22.29119873046875秒
程序运行时间:22.292198181152344秒
程序运行时间:22.292198181152344秒
程序运行时间:22.293198347091675秒
程序运行时间:22.293198347091675秒
程序运行时间:22.294198513031006秒
程序运行时间:22.295199155807495秒
程序运行时间:22.296199083328247秒
程序运行时间:22.296199083328247秒
程序运行时间:22.297199249267578秒
程序运行时间:22.297199249267578秒
程序运行时间:22.29819941520691秒
程序运行时间:22.29819941520691秒
程序运行时间:22.299200296401978秒
程序运行时间:22.299200296401978秒
程序运行时间:22.30020022392273秒
程序运行时间:22.30020022392273秒
程序运行时间:22.30120038986206秒
程序运行时间:22.30120038986206秒
程序运行时间:22.302200317382812秒
程序运行时间:22.302200317382812秒
程序运行时间:22.303200721740723秒
程序运行时间:22.303200721740723秒
程序运行时间:22.304200887680054秒
程序运行时间:22.304200887680054秒
程序运行时间:22.305201053619385秒
程序运行时间:22.305201053619385秒
程序运行时间:22.306201219558716秒
程序运行时间:22.306201219558716秒
程序运行时间:22.307202100753784秒
程序运行时间:22.307202100753784秒
程序运行时间:22.308201551437378秒
程序运行时间:22.308201551437378秒
程序运行时间:22.309201955795288秒
程序运行时间:22.31020212173462秒
程序运行时间:22.31020212173462秒
程序运行时间:22.31120252609253秒
程序运行时间:22.31120252609253秒
程序运行时间:22.31220269203186秒
程序运行时间:22.31220269203186秒
程序运行时间:22.31320309638977秒
程序运行时间:22.31320309638977秒
程序运行时间:22.314203023910522秒
程序运行时间:22.314203023910522秒
程序运行时间:22.3162043094635秒
程序运行时间:22.317203998565674秒
程序运行时间:22.3182053565979秒
程序运行时间:22.3182053565979秒
程序运行时间:22.319204568862915秒
程序运行时间:22.319204568862915秒
程序运行时间:22.320204734802246秒
程序运行时间:22.320204734802246秒
程序运行时间:22.321204662322998秒
程序运行时间:22.321204662322998秒
程序运行时间:22.32220482826233秒
程序运行时间:22.32220482826233秒
程序运行时间:22.32320499420166秒
程序运行时间:22.32320499420166秒
程序运行时间:22.32420539855957秒
程序运行时间:22.32420539855957秒
程序运行时间:22.325205326080322秒
程序运行时间:22.325205326080322秒
程序运行时间:22.326205730438232秒
程序运行时间:22.326205730438232秒
程序运行时间:22.327205896377563秒
程序运行时间:22.327205896377563秒
程序运行时间:22.328206300735474秒
程序运行时间:22.328206300735474秒
程序运行时间:22.329206466674805秒
程序运行时间:22.329206466674805秒
程序运行时间:22.330206632614136秒
程序运行时间:22.330206632614136秒
程序运行时间:22.331206798553467秒
程序运行时间:22.331206798553467秒
程序运行时间:22.332206964492798秒
程序运行时间:22.332206964492798秒
程序运行时间:22.33320713043213秒
程序运行时间:22.33320713043213秒
程序运行时间:22.33420753479004秒
程序运行时间:22.33420753479004秒
程序运行时间:22.33520793914795秒
程序运行时间:22.33520793914795秒
程序运行时间:22.3362078666687秒
程序运行时间:22.3362078666687秒
程序运行时间:22.33720827102661秒
程序运行时间:22.33720827102661秒
程序运行时间:22.338208436965942秒
程序运行时间:22.33920907974243秒
程序运行时间:22.33920907974243秒
程序运行时间:22.340208768844604秒
程序运行时间:22.340208768844604秒
程序运行时间:22.341208934783936秒
程序运行时间:22.341208934783936秒
程序运行时间:22.342209100723267秒
程序运行时间:22.342209100723267秒
程序运行时间:22.343209743499756秒
程序运行时间:22.343209743499756秒
程序运行时间:22.344209909439087秒
程序运行时间:22.344209909439087秒
程序运行时间:22.345210075378418秒
程序运行时间:22.345210075378418秒
程序运行时间:22.34621024131775秒
程序运行时间:22.34621024131775秒
程序运行时间:22.34721040725708秒
程序运行时间:22.34721040725708秒
程序运行时间:22.34821057319641秒
程序运行时间:22.34821057319641秒
程序运行时间:22.349210739135742秒
程序运行时间:22.349210739135742秒
程序运行时间:22.350210905075073秒
程序运行时间:22.350210905075073秒
程序运行时间:22.351211547851562秒
程序运行时间:22.352211713790894秒
程序运行时间:22.352211713790894秒
程序运行时间:22.353211879730225秒
程序运行时间:22.354889154434204秒
程序运行时间:22.355212450027466秒
程序运行时间:22.356212615966797秒
程序运行时间:22.357213020324707秒
程序运行时间:22.357213020324707秒
程序运行时间:22.35821294784546秒
程序运行时间:22.35821294784546秒
程序运行时间:22.35921335220337秒
程序运行时间:22.35921335220337秒
程序运行时间:22.36021375656128秒
程序运行时间:22.36021375656128秒
程序运行时间:22.36121368408203秒
程序运行时间:22.36121368408203秒
程序运行时间:22.36221432685852秒
程序运行时间:22.363214254379272秒
程序运行时间:22.363214254379272秒
程序运行时间:22.364214420318604秒
程序运行时间:22.364214420318604秒
程序运行时间:22.365214347839355秒
程序运行时间:22.365214347839355秒
程序运行时间:22.366214513778687秒
程序运行时间:22.366214513778687秒
程序运行时间:22.367215156555176秒
程序运行时间:22.367215156555176秒
程序运行时间:22.368215322494507秒
程序运行时间:22.368215322494507秒
程序运行时间:22.369215488433838秒
程序运行时间:22.37021565437317秒
程序运行时间:22.3712158203125秒
程序运行时间:22.3712158203125秒
程序运行时间:22.37221622467041秒
程序运行时间:22.37221622467041秒
程序运行时间:22.37321639060974秒
程序运行时间:22.37321639060974秒
程序运行时间:22.374216556549072秒
程序运行时间:22.375216722488403秒
程序运行时间:22.376217126846313秒
程序运行时间:22.376217126846313秒
程序运行时间:22.377217292785645秒
程序运行时间:22.377217292785645秒
程序运行时间:22.378217458724976秒
程序运行时间:22.378217458724976秒
程序运行时间:22.379217624664307秒
程序运行时间:22.379217624664307秒
程序运行时间:22.380217790603638秒
程序运行时间:22.380217790603638秒
程序运行时间:22.38121795654297秒
程序运行时间:22.38221836090088秒
程序运行时间:22.38321852684021秒
程序运行时间:22.38321852684021秒
程序运行时间:22.38421893119812秒
程序运行时间:22.385220289230347秒
程序运行时间:22.386219263076782秒
程序运行时间:22.386219263076782秒
程序运行时间:22.387219429016113秒
程序运行时间:22.387219429016113秒
程序运行时间:22.387219429016113秒
程序运行时间:22.38822031021118秒
程序运行时间:22.389220476150513秒
程序运行时间:22.389220476150513秒
程序运行时间:22.389220476150513秒
程序运行时间:22.390220642089844秒
程序运行时间:22.390220642089844秒
程序运行时间:22.391221046447754秒
程序运行时间:22.391221046447754秒
程序运行时间:22.391221046447754秒
程序运行时间:22.392221212387085秒
程序运行时间:22.392221212387085秒
程序运行时间:22.392221212387085秒
程序运行时间:22.393221616744995秒
程序运行时间:22.393221616744995秒
程序运行时间:22.394221782684326秒
程序运行时间:22.394221782684326秒
程序运行时间:22.394221782684326秒
程序运行时间:22.395221948623657秒
程序运行时间:22.395221948623657秒
程序运行时间:22.39622163772583秒
程序运行时间:22.39622163772583秒
程序运行时间:22.39622163772583秒
程序运行时间:22.397223949432373秒
程序运行时间:22.397223949432373秒
程序运行时间:22.397223949432373秒
程序运行时间:22.398221731185913秒
程序运行时间:22.399222135543823秒
程序运行时间:22.399222135543823秒
程序运行时间:22.399222135543823秒
程序运行时间:22.40022325515747秒
程序运行时间:22.40022325515747秒
程序运行时间:22.401224374771118秒
程序运行时间:22.401224374771118秒
程序运行时间:22.402225017547607秒
程序运行时间:22.402225017547607秒
程序运行时间:22.40322494506836秒
程序运行时间:22.40322494506836秒
程序运行时间:22.40322494506836秒
程序运行时间:22.404223442077637秒
程序运行时间:22.404223442077637秒
程序运行时间:22.40522336959839秒
程序运行时间:22.40522336959839秒
程序运行时间:22.40522336959839秒
程序运行时间:22.406224250793457秒
程序运行时间:22.406224250793457秒
程序运行时间:22.40722370147705秒
程序运行时间:22.40722370147705秒
程序运行时间:22.40722370147705秒
程序运行时间:22.4082248210907秒
程序运行时间:22.40922522544861秒
程序运行时间:22.40922522544861秒
程序运行时间:22.40922522544861秒
程序运行时间:22.41022539138794秒
程序运行时间:22.41022539138794秒
程序运行时间:22.41122555732727秒
程序运行时间:22.41122555732727秒
程序运行时间:22.41122555732727秒
程序运行时间:22.4122257232666秒
程序运行时间:22.413225650787354秒
程序运行时间:22.413225650787354秒
程序运行时间:22.413225650787354秒
程序运行时间:22.41422748565674秒
程序运行时间:22.41422748565674秒
程序运行时间:22.41422748565674秒
程序运行时间:22.415225744247437秒
程序运行时间:22.415225744247437秒
程序运行时间:22.41722869873047秒
程序运行时间:22.418227195739746秒
程序运行时间:22.418227195739746秒
程序运行时间:22.41922688484192秒
程序运行时间:22.41922688484192秒
程序运行时间:22.420228004455566秒
程序运行时间:22.420228004455566秒
程序运行时间:22.421228408813477秒
程序运行时间:22.421228408813477秒
程序运行时间:22.42222809791565秒
程序运行时间:22.42222809791565秒
程序运行时间:22.42322826385498秒
程序运行时间:22.42422842979431秒
程序运行时间:22.42522954940796秒
程序运行时间:22.42522954940796秒
程序运行时间:22.42622947692871秒
程序运行时间:22.42722988128662秒
程序运行时间:22.42722988128662秒
程序运行时间:22.428229570388794秒
程序运行时间:22.428229570388794秒
程序运行时间:22.429230213165283秒
程序运行时间:22.429230213165283秒
程序运行时间:22.430229902267456秒
程序运行时间:22.430229902267456秒
程序运行时间:22.431230068206787秒
程序运行时间:22.432230234146118秒
程序运行时间:22.432230234146118秒
程序运行时间:22.43323254585266秒
程序运行时间:22.434231519699097秒
程序运行时间:22.434231519699097秒
程序运行时间:22.43523144721985秒
程序运行时间:22.43523144721985秒
程序运行时间:22.436230421066284秒
程序运行时间:22.436230421066284秒
程序运行时间:22.43723201751709秒
程序运行时间:22.43723201751709秒
程序运行时间:22.438231706619263秒
程序运行时间:22.438231706619263秒
程序运行时间:22.439231872558594秒
程序运行时间:22.439231872558594秒
程序运行时间:22.440232038497925秒
程序运行时间:22.440232038497925秒
程序运行时间:22.441232919692993秒
程序运行时间:22.441232919692993秒
程序运行时间:22.442233085632324秒
程序运行时间:22.442233085632324秒
程序运行时间:22.443233013153076秒
程序运行时间:22.443233013153076秒
程序运行时间:22.444232940673828秒
程序运行时间:22.444232940673828秒
程序运行时间:22.44523334503174秒
程序运行时间:22.44523334503174秒
程序运行时间:22.446233987808228秒
程序运行时间:22.446233987808228秒
程序运行时间:22.44723415374756秒
程序运行时间:22.44723415374756秒
程序运行时间:22.44823384284973秒
程序运行时间:22.449235200881958秒
程序运行时间:22.449235200881958秒
程序运行时间:22.450234413146973秒
程序运行时间:22.450234413146973秒
程序运行时间:22.451234579086304秒
程序运行时间:22.451234579086304秒
程序运行时间:22.45223569869995秒
程序运行时间:22.45223569869995秒
程序运行时间:22.453235626220703秒
程序运行时间:22.453235626220703秒
程序运行时间:22.454235315322876秒
程序运行时间:22.454235315322876秒
程序运行时间:22.4552481174469秒
程序运行时间:22.4552481174469秒
程序运行时间:22.45624804496765秒
程序运行时间:22.45624804496765秒
程序运行时间:22.45725393295288秒
程序运行时间:22.45725393295288秒
程序运行时间:22.458254098892212秒
程序运行时间:22.458254098892212秒
程序运行时间:22.459248542785645秒
程序运行时间:22.459248542785645秒
程序运行时间:22.460248708724976秒
程序运行时间:22.460248708724976秒
程序运行时间:22.461248874664307秒
程序运行时间:22.461248874664307秒
程序运行时间:22.462254762649536秒
程序运行时间:22.462254762649536秒
程序运行时间:22.463254928588867秒
程序运行时间:22.463254928588867秒
程序运行时间:22.46424961090088秒
程序运行时间:22.46424961090088秒
程序运行时间:22.46524977684021秒
程序运行时间:22.46625018119812秒
程序运行时间:22.46725034713745秒
程序运行时间:22.46725034713745秒
程序运行时间:22.4682559967041秒
程序运行时间:22.4682559967041秒
程序运行时间:22.46925640106201秒
程序运行时间:22.46925640106201秒
程序运行时间:22.470250844955444秒
程序运行时间:22.470250844955444秒
程序运行时间:22.471251487731934秒
程序运行时间:22.471251487731934秒
程序运行时间:22.472251653671265秒
程序运行时间:22.472251653671265秒
程序运行时间:22.473257303237915秒
程序运行时间:22.473257303237915秒
程序运行时间:22.474257230758667秒
程序运行时间:22.474257230758667秒
程序运行时间:22.475252151489258秒
程序运行时间:22.475252151489258秒
程序运行时间:22.476252555847168秒
程序运行时间:22.47725248336792秒
程序运行时间:22.47725248336792秒
程序运行时间:22.47825837135315秒
程序运行时间:22.47825837135315秒
程序运行时间:22.47925853729248秒
程序运行时间:22.47925853729248秒
程序运行时间:22.48025345802307秒
程序运行时间:22.482253789901733秒
程序运行时间:22.482253789901733秒
程序运行时间:22.483247995376587秒
程序运行时间:22.483247995376587秒
程序运行时间:22.484259843826294秒
程序运行时间:22.484259843826294秒
程序运行时间:22.485260009765625秒
程序运行时间:22.485260009765625秒
程序运行时间:22.486254453659058秒
程序运行时间:22.486254453659058秒
程序运行时间:22.487254858016968秒
程序运行时间:22.487254858016968秒
程序运行时间:22.488255262374878秒
程序运行时间:22.488255262374878秒
程序运行时间:22.48926091194153秒
程序运行时间:22.48926091194153秒
程序运行时间:22.49026083946228秒
程序运行时间:22.49026083946228秒
程序运行时间:22.49125576019287秒
程序运行时间:22.49125576019287秒
程序运行时间:22.492255926132202秒
程序运行时间:22.492255926132202秒
程序运行时间:22.493256092071533秒
程序运行时间:22.493256092071533秒
程序运行时间:22.494261980056763秒
程序运行时间:22.494261980056763秒
程序运行时间:22.495262145996094秒
程序运行时间:22.495262145996094秒
程序运行时间:22.496256589889526秒
程序运行时间:22.496256589889526秒
程序运行时间:22.497256994247437秒
程序运行时间:22.497256994247437秒
程序运行时间:22.498257160186768秒
程序运行时间:22.498257160186768秒
程序运行时间:22.4992516040802秒
程序运行时间:22.4992516040802秒
程序运行时间:22.500263452529907秒
程序运行时间:22.500263452529907秒
程序运行时间:22.50126361846924秒
程序运行时间:22.50126361846924秒
程序运行时间:22.50225806236267秒
程序运行时间:22.50225806236267秒
程序运行时间:22.50325846672058秒
程序运行时间:22.50325846672058秒
程序运行时间:22.50426411628723秒
程序运行时间:22.50426411628723秒
程序运行时间:22.50526452064514秒
程序运行时间:22.50526452064514秒
程序运行时间:22.506259202957153秒
程序运行时间:22.507259130477905秒
程序运行时间:22.507259130477905秒
程序运行时间:22.508265256881714秒
程序运行时间:22.508265256881714秒
程序运行时间:22.509265422821045秒
程序运行时间:22.509265422821045秒
程序运行时间:22.510259866714478秒
程序运行时间:22.510259866714478秒
程序运行时间:22.51126003265381秒
程序运行时间:22.51126003265381秒
程序运行时间:22.512250900268555秒
程序运行时间:22.512250900268555秒
程序运行时间:22.51326632499695秒
程序运行时间:22.51326632499695秒
程序运行时间:22.514254808425903秒
程序运行时间:22.514254808425903秒
程序运行时间:22.515255212783813秒
程序运行时间:22.515255212783813秒
程序运行时间:22.516261339187622秒
程序运行时间:22.516261339187622秒
程序运行时间:22.51726722717285秒
程序运行时间:22.51726722717285秒
程序运行时间:22.518267393112183秒
程序运行时间:22.518267393112183秒
程序运行时间:22.519262075424194秒
程序运行时间:22.519262075424194秒
程序运行时间:22.520262241363525秒
程序运行时间:22.520262241363525秒
程序运行时间:22.521262645721436秒
程序运行时间:22.521262645721436秒
程序运行时间:22.522268295288086秒
程序运行时间:22.522268295288086秒
程序运行时间:22.523268461227417秒
程序运行时间:22.523268461227417秒
程序运行时间:22.52426314353943秒
程序运行时间:22.52426314353943秒
程序运行时间:22.52626919746399秒
程序运行时间:22.52626919746399秒
程序运行时间:22.52726912498474秒
程序运行时间:22.528264045715332秒
程序运行时间:22.528264045715332秒
程序运行时间:22.529258251190186秒
程序运行时间:22.529258251190186秒
程序运行时间:22.530269861221313秒
程序运行时间:22.530269861221313秒
程序运行时间:22.531264781951904秒
程序运行时间:22.531264781951904秒
程序运行时间:22.532270431518555秒
程序运行时间:22.532270431518555秒
程序运行时间:22.533270835876465秒
程序运行时间:22.533270835876465秒
程序运行时间:22.534265518188477秒
程序运行时间:22.53526544570923秒
程序运行时间:22.536271333694458秒
程序运行时间:22.536271333694458秒
程序运行时间:22.53727149963379秒
程序运行时间:22.53727149963379秒
程序运行时间:22.53827166557312秒
程序运行时间:22.53926658630371秒
程序运行时间:22.540260791778564秒
程序运行时间:22.541272401809692秒
程序运行时间:22.541272401809692秒
程序运行时间:22.54230523109436秒
程序运行时间:22.543261289596558秒
程序运行时间:22.543261289596558秒
程序运行时间:22.544267416000366秒
程序运行时间:22.544267416000366秒
程序运行时间:22.545262098312378秒
程序运行时间:22.545262098312378秒
程序运行时间:22.54626774787903秒
程序运行时间:22.54626774787903秒
程序运行时间:22.547268390655518秒
程序运行时间:22.547268390655518秒
程序运行时间:22.54826855659485秒
程序运行时间:22.54826855659485秒
程序运行时间:22.5492742061615秒
程序运行时间:22.55026888847351秒
程序运行时间:22.55026888847351秒
程序运行时间:22.551263093948364秒
程序运行时间:22.551263093948364秒
程序运行时间:22.552269458770752秒
程序运行时间:22.552269458770752秒
程序运行时间:22.553263664245605秒
程序运行时间:22.553263664245605秒
程序运行时间:22.554269790649414秒
程序运行时间:22.554269790649414秒
程序运行时间:22.555270195007324秒
程序运行时间:22.555270195007324秒
程序运行时间:22.556270360946655秒
程序运行时间:22.556270360946655秒
程序运行时间:22.557270526885986秒
程序运行时间:22.557270526885986秒
程序运行时间:22.558270692825317秒
程序运行时间:22.558270692825317秒
程序运行时间:22.559265613555908秒
程序运行时间:22.559265613555908秒
程序运行时间:22.560271501541138秒
程序运行时间:22.561265230178833秒
程序运行时间:22.561265230178833秒
程序运行时间:22.56227135658264秒
程序运行时间:22.56227135658264秒
程序运行时间:22.56327176094055秒
程序运行时间:22.56327176094055秒
程序运行时间:22.564272165298462秒
程序运行时间:22.564272165298462秒
程序运行时间:22.565272331237793秒
程序运行时间:22.565272331237793秒
程序运行时间:22.566272497177124秒
程序运行时间:22.566272497177124秒
程序运行时间:22.567272901535034秒
程序运行时间:22.567272901535034秒
程序运行时间:22.568273067474365秒
程序运行时间:22.568273067474365秒
程序运行时间:22.569278717041016秒
程序运行时间:22.569278717041016秒
程序运行时间:22.570273876190186秒
程序运行时间:22.57127356529236秒
程序运行时间:22.57127356529236秒
程序运行时间:22.57227921485901秒
程序运行时间:22.57227921485901秒
程序运行时间:22.5732684135437秒
程序运行时间:22.5732684135437秒
程序运行时间:22.57427430152893秒
程序运行时间:22.57427430152893秒
程序运行时间:22.575268507003784秒
程序运行时间:22.575268507003784秒
程序运行时间:22.576274871826172秒
程序运行时间:22.576274871826172秒
程序运行时间:22.577275037765503秒
程序运行时间:22.577275037765503秒
程序运行时间:22.578275203704834秒
程序运行时间:22.578275203704834秒
程序运行时间:22.579275369644165秒
程序运行时间:22.579275369644165秒
程序运行时间:22.580281019210815秒
程序运行时间:22.580281019210815秒
程序运行时间:22.581275939941406秒
程序运行时间:22.581275939941406秒
程序运行时间:22.582276105880737秒
程序运行时间:22.582276105880737秒
程序运行时间:22.583276510238647秒
程序运行时间:22.583276510238647秒
程序运行时间:22.584270477294922秒
程序运行时间:22.584270477294922秒
程序运行时间:22.58527684211731秒
程序运行时间:22.58527684211731秒
程序运行时间:22.586271286010742秒
程序运行时间:22.586271286010742秒
程序运行时间:22.587282180786133秒
程序运行时间:22.587282180786133秒
程序运行时间:22.58829617500305秒
程序运行时间:22.589282989501953秒
程序运行时间:22.589282989501953秒
程序运行时间:22.590277910232544秒
程序运行时间:22.590277910232544秒
程序运行时间:22.591272115707397秒
程序运行时间:22.591272115707397秒
程序运行时间:22.592278718948364秒
程序运行时间:22.592278718948364秒
程序运行时间:22.593278646469116秒
程序运行时间:22.593278646469116秒
程序运行时间:22.594278812408447秒
程序运行时间:22.594278812408447秒
程序运行时间:22.595279216766357秒
程序运行时间:22.595279216766357秒
程序运行时间:22.59627914428711秒
程序运行时间:22.59627914428711秒
程序运行时间:22.59727931022644秒
程序运行时间:22.59727931022644秒
程序运行时间:22.59827995300293秒
程序运行时间:22.59827995300293秒
程序运行时间:22.599285364151秒
程序运行时间:22.599285364151秒
程序运行时间:22.600280284881592秒
程序运行时间:22.600280284881592秒
程序运行时间:22.601280450820923秒
程序运行时间:22.601280450820923秒
程序运行时间:22.602286338806152秒
程序运行时间:22.602286338806152秒
程序运行时间:22.603280782699585秒
程序运行时间:22.60426950454712秒
程序运行时间:22.605268955230713秒
程序运行时间:22.606268644332886秒
程序运行时间:22.606268644332886秒
程序运行时间:22.607268810272217秒
程序运行时间:22.607268810272217秒
程序运行时间:22.608268976211548秒
程序运行时间:22.608268976211548秒
程序运行时间:22.60926914215088秒
程序运行时间:22.60926914215088秒
程序运行时间:22.61026930809021秒
程序运行时间:22.61026930809021秒
程序运行时间:22.61126947402954秒
程序运行时间:22.61126947402954秒
程序运行时间:22.61227011680603秒
程序运行时间:22.61227011680603秒
程序运行时间:22.61327028274536秒
程序运行时间:22.61327028274536秒
程序运行时间:22.61427068710327秒
程序运行时间:22.61427068710327秒
程序运行时间:22.615270614624023秒
程序运行时间:22.615270614624023秒
程序运行时间:22.616270780563354秒
程序运行时间:22.616270780563354秒
程序运行时间:22.617270946502686秒
程序运行时间:22.617270946502686秒
程序运行时间:22.618271112442017秒
程序运行时间:22.618271112442017秒
程序运行时间:22.619271278381348秒
程序运行时间:22.62027382850647秒
程序运行时间:22.62027382850647秒
程序运行时间:22.621280908584595秒
程序运行时间:22.621280908584595秒
程序运行时间:22.621280908584595秒
程序运行时间:22.622279405593872秒
程序运行时间:22.622279405593872秒
程序运行时间:22.62328553199768秒
程序运行时间:22.62328553199768秒
程序运行时间:22.62328553199768秒
程序运行时间:22.62428569793701秒
程序运行时间:22.62428569793701秒
程序运行时间:22.625285863876343秒
程序运行时间:22.625285863876343秒
程序运行时间:22.625285863876343秒
程序运行时间:22.626286029815674秒
程序运行时间:22.626286029815674秒
程序运行时间:22.626286029815674秒
程序运行时间:22.627286434173584秒
程序运行时间:22.627286434173584秒
程序运行时间:22.628286600112915秒
程序运行时间:22.628286600112915秒
程序运行时间:22.628286600112915秒
程序运行时间:22.629286766052246秒
程序运行时间:22.629286766052246秒
程序运行时间:22.630287647247314秒
程序运行时间:22.630287647247314秒
程序运行时间:22.631287336349487秒
程序运行时间:22.631287336349487秒
程序运行时间:22.63228750228882秒
程序运行时间:22.63228750228882秒
程序运行时间:22.63228750228882秒
程序运行时间:22.63328766822815秒
程序运行时间:22.63428783416748秒
程序运行时间:22.63428783416748秒
程序运行时间:22.63428783416748秒
程序运行时间:22.63528823852539秒
程序运行时间:22.63528823852539秒
程序运行时间:22.636290311813354秒
程序运行时间:22.636290311813354秒
程序运行时间:22.637288570404053秒
程序运行时间:22.637288570404053秒
程序运行时间:22.637288570404053秒
程序运行时间:22.638288736343384秒
程序运行时间:22.639289140701294秒
程序运行时间:22.639289140701294秒
程序运行时间:22.639289140701294秒
程序运行时间:22.640289545059204秒
程序运行时间:22.640289545059204秒
程序运行时间:22.641289234161377秒
程序运行时间:22.641289234161377秒
程序运行时间:22.641289234161377秒
程序运行时间:22.642289638519287秒
程序运行时间:22.642289638519287秒
程序运行时间:22.643289804458618秒
程序运行时间:22.643289804458618秒
程序运行时间:22.643289804458618秒
程序运行时间:22.64429020881653秒
程序运行时间:22.64429020881653秒
程序运行时间:22.64529013633728秒
程序运行时间:22.64529013633728秒
程序运行时间:22.64529013633728秒
程序运行时间:22.64629030227661秒
程序运行时间:22.64629030227661秒
程序运行时间:22.64729070663452秒
程序运行时间:22.64729070663452秒
程序运行时间:22.64729070663452秒
程序运行时间:22.64829111099243秒
程序运行时间:22.64829111099243秒
程序运行时间:22.64829111099243秒
程序运行时间:22.649291276931763秒
程序运行时间:22.649291276931763秒
程序运行时间:22.650291681289673秒
程序运行时间:22.650291681289673秒
程序运行时间:22.650291681289673秒
程序运行时间:22.651291608810425秒
程序运行时间:22.651291608810425秒
程序运行时间:22.652279138565063秒
程序运行时间:22.652279138565063秒
程序运行时间:22.652279138565063秒
程序运行时间:22.65328598022461秒
程序运行时间:22.65328598022461秒
程序运行时间:22.6542866230011秒
程序运行时间:22.6542866230011秒
程序运行时间:22.655292510986328秒
程序运行时间:22.655292510986328秒
程序运行时间:22.65629291534424秒
程序运行时间:22.65629291534424秒
程序运行时间:22.65729331970215秒
程序运行时间:22.65729331970215秒
程序运行时间:22.6582932472229秒
程序运行时间:22.6582932472229秒
程序运行时间:22.65929388999939秒
程序运行时间:22.65929388999939秒
程序运行时间:22.66029381752014秒
程序运行时间:22.66029381752014秒
程序运行时间:22.66029381752014秒
程序运行时间:22.661293745040894秒
程序运行时间:22.661293745040894秒
程序运行时间:22.662294149398804秒
程序运行时间:22.662294149398804秒
程序运行时间:22.663294315338135秒
程序运行时间:22.663294315338135秒
程序运行时间:22.664294481277466秒
程序运行时间:22.664294481277466秒
程序运行时间:22.664294481277466秒
程序运行时间:22.665294885635376秒
程序运行时间:22.665294885635376秒
程序运行时间:22.666295051574707秒
程序运行时间:22.666295051574707秒
程序运行时间:22.667295455932617秒
程序运行时间:22.667295455932617秒
程序运行时间:22.668283700942993秒
程序运行时间:22.669285535812378秒
程序运行时间:22.669285535812378秒
程序运行时间:22.670296907424927秒
程序运行时间:22.671294927597046秒
程序运行时间:22.671294927597046秒
程序运行时间:22.671294927597046秒
程序运行时间:22.67228651046753秒
程序运行时间:22.67228651046753秒
程序运行时间:22.6732976436615秒
程序运行时间:22.6732976436615秒
程序运行时间:22.674291133880615秒
程序运行时间:22.674291133880615秒
程序运行时间:22.674291133880615秒
程序运行时间:22.675297260284424秒
程序运行时间:22.675297260284424秒
程序运行时间:22.675297260284424秒
程序运行时间:22.676297426223755秒
程序运行时间:22.676297426223755秒
程序运行时间:22.677297353744507秒
程序运行时间:22.677297353744507秒
程序运行时间:22.677297353744507秒

程序运行时间:22.809937000274658秒
程序运行时间:22.811939477920532秒
程序运行时间:22.811939477920532秒
程序运行时间:22.812939882278442秒
程序运行时间:22.812939882278442秒
程序运行时间:22.81394052505493秒
程序运行时间:22.81394052505493秒
程序运行时间:22.814940452575684秒
程序运行时间:22.814940452575684秒
程序运行时间:22.815940856933594秒
程序运行时间:22.816941022872925秒
程序运行时间:22.816941022872925秒
程序运行时间:22.817941188812256秒
程序运行时间:22.817941188812256秒
程序运行时间:22.818941354751587秒
程序运行时间:22.818941354751587秒
程序运行时间:22.819941759109497秒
程序运行时间:22.820415258407593秒
程序运行时间:22.820918798446655秒
程序运行时间:22.821919918060303秒
程序运行时间:22.821919918060303秒
程序运行时间:22.822920083999634秒
程序运行时间:22.822920083999634秒
程序运行时间:22.823920488357544秒
程序运行时间:22.823920488357544秒
程序运行时间:22.824920654296875秒
程序运行时间:22.82592248916626秒
程序运行时间:22.82592248916626秒
程序运行时间:22.826929092407227秒
程序运行时间:22.826929092407227秒
程序运行时间:22.826929092407227秒
程序运行时间:22.82792830467224秒
程序运行时间:22.82792830467224秒
程序运行时间:22.82892918586731秒
程序运行时间:22.82892918586731秒
程序运行时间:22.82993483543396秒
程序运行时间:22.82993483543396秒
程序运行时间:22.83093523979187秒
程序运行时间:22.83093523979187秒
程序运行时间:22.83093523979187秒
程序运行时间:22.831935167312622秒
程序运行时间:22.831935167312622秒
程序运行时间:22.832935333251953秒
程序运行时间:22.832935333251953秒
程序运行时间:22.832935333251953秒
程序运行时间:22.833935499191284秒
程序运行时间:22.833935499191284秒
程序运行时间:22.833935499191284秒
程序运行时间:22.835119485855103秒
程序运行时间:22.835935831069946秒
程序运行时间:22.836930751800537秒
程序运行时间:22.836930751800537秒
程序运行时间:22.836930751800537秒
程序运行时间:22.837936639785767秒
程序运行时间:22.837936639785767秒
程序运行时间:22.838937282562256秒
程序运行时间:22.838937282562256秒
程序运行时间:22.838937282562256秒
程序运行时间:22.83993697166443秒
程序运行时间:22.83993697166443秒
程序运行时间:22.840938806533813秒
程序运行时间:22.840938806533813秒
程序运行时间:22.840938806533813秒
程序运行时间:22.84193754196167秒
程序运行时间:22.84193754196167秒
程序运行时间:22.84293222427368秒
程序运行时间:22.84293222427368秒
程序运行时间:22.84293222427368秒
程序运行时间:22.843937873840332秒
程序运行时间:22.844938278198242秒
程序运行时间:22.844938278198242秒
程序运行时间:22.844938278198242秒
程序运行时间:22.845950603485107秒
程序运行时间:22.845950603485107秒
程序运行时间:22.846938610076904秒
程序运行时间:22.847927808761597秒
程序运行时间:22.847927808761597秒
程序运行时间:22.847927808761597秒
程序运行时间:22.84893298149109秒
程序运行时间:22.84893298149109秒
程序运行时间:22.84992742538452秒
程序运行时间:22.84992742538452秒
程序运行时间:22.84992742538452秒
程序运行时间:22.85093355178833秒
程序运行时间:22.85093355178833秒
程序运行时间:22.85093355178833秒
程序运行时间:22.851927518844604秒
程序运行时间:22.851927518844604秒
程序运行时间:22.852946996688843秒
程序运行时间:22.853927850723267秒
程序运行时间:22.853927850723267秒
程序运行时间:22.853927850723267秒
程序运行时间:22.854934692382812秒
程序运行时间:22.854934692382812秒
程序运行时间:22.854934692382812秒
程序运行时间:22.855929851531982秒
程序运行时间:22.85692858695984秒
程序运行时间:22.85692858695984秒
程序运行时间:22.857928037643433秒
程序运行时间:22.857928037643433秒
程序运行时间:22.858928203582764秒
程序运行时间:22.858928203582764秒
程序运行时间:22.859928846359253秒
程序运行时间:22.859928846359253秒
程序运行时间:22.860929012298584秒
程序运行时间:22.860929012298584秒
程序运行时间:22.861929178237915秒
程序运行时间:22.861929178237915秒
程序运行时间:22.862929344177246秒
程序运行时间:22.862929344177246秒
程序运行时间:22.863929510116577秒
程序运行时间:22.863929510116577秒
程序运行时间:22.864929676055908秒
程序运行时间:22.864929676055908秒
程序运行时间:22.86592984199524秒
程序运行时间:22.86592984199524秒
程序运行时间:22.86693000793457秒
程序运行时间:22.86693000793457秒
程序运行时间:22.86793041229248秒
程序运行时间:22.86793041229248秒
程序运行时间:22.86893081665039秒
程序运行时间:22.869930744171143秒
程序运行时间:22.870931148529053秒
程序运行时间:22.870931148529053秒
程序运行时间:22.871931314468384秒
程序运行时间:22.872938871383667秒
程序运行时间:22.87393879890442秒
程序运行时间:22.87493896484375秒
程序运行时间:22.87493896484375秒
程序运行时间:22.87493896484375秒
程序运行时间:22.87594509124756秒
程序运行时间:22.87594509124756秒
程序运行时间:22.87694525718689秒
程序运行时间:22.87694525718689秒
程序运行时间:22.87794542312622秒
程序运行时间:22.87794542312622秒
程序运行时间:22.87894582748413秒
程序运行时间:22.87894582748413秒
程序运行时间:22.87994647026062秒
程序运行时间:22.880946397781372秒
程序运行时间:22.880946397781372秒
程序运行时间:22.88193416595459秒
程序运行时间:22.882952451705933秒
程序运行时间:22.882952451705933秒
程序运行时间:22.883946895599365秒
程序运行时间:22.883946895599365秒
程序运行时间:22.884941339492798秒
程序运行时间:22.884941339492798秒
程序运行时间:22.884941339492798秒
程序运行时间:22.885947227478027秒
程序运行时间:22.885947227478027秒
程序运行时间:22.885947227478027秒
程序运行时间:22.886953115463257秒
程序运行时间:22.886953115463257秒
程序运行时间:22.887953281402588秒
程序运行时间:22.887953281402588秒
程序运行时间:22.887953281402588秒
程序运行时间:22.88894820213318秒
程序运行时间:22.88894820213318秒
程序运行时间:22.88994836807251秒
程序运行时间:22.88994836807251秒
程序运行时间:22.89094829559326秒
程序运行时间:22.89094829559326秒
程序运行时间:22.89195442199707秒
程序运行时间:22.89195442199707秒
程序运行时间:22.89195442199707秒
程序运行时间:22.892948865890503秒
程序运行时间:22.892948865890503秒
程序运行时间:22.893949270248413秒
程序运行时间:22.893949270248413秒
程序运行时间:22.894954919815063秒
程序运行时间:22.894954919815063秒
程序运行时间:22.895954847335815秒
程序运行时间:22.895954847335815秒
程序运行时间:22.895954847335815秒
程序运行时间:22.896950006484985秒
程序运行时间:22.896950006484985秒
程序运行时间:22.897950172424316秒
程序运行时间:22.897950172424316秒
程序运行时间:22.897950172424316秒
程序运行时间:22.898950338363647秒
程序运行时间:22.898950338363647秒
程序运行时间:22.898950338363647秒
程序运行时间:22.89995050430298秒
程序运行时间:22.89995050430298秒
程序运行时间:22.900956392288208秒
程序运行时间:22.900956392288208秒
程序运行时间:22.900956392288208秒
程序运行时间:22.90195083618164秒
程序运行时间:22.90195083618164秒
程序运行时间:22.90295124053955秒
程序运行时间:22.90295124053955秒
程序运行时间:22.90295124053955秒
程序运行时间:22.90395164489746秒
程序运行时间:22.90395164489746秒
程序运行时间:22.904956817626953秒
程序运行时间:22.904956817626953秒
程序运行时间:22.904956817626953秒
程序运行时间:22.905951738357544秒
程序运行时间:22.905951738357544秒
程序运行时间:22.905951738357544秒
程序运行时间:22.906952142715454秒
程序运行时间:22.906952142715454秒
程序运行时间:22.907952308654785秒
程序运行时间:22.907952308654785秒
程序运行时间:22.907952308654785秒
程序运行时间:22.908952474594116秒
程序运行时间:22.908952474594116秒
程序运行时间:22.909958362579346秒
程序运行时间:22.909958362579346秒
程序运行时间:22.909958362579346秒
程序运行时间:22.91095280647278秒
程序运行时间:22.91095280647278秒
程序运行时间:22.911953449249268秒
程序运行时间:22.911953449249268秒
程序运行时间:22.911953449249268秒
程序运行时间:22.91295337677002秒
程序运行时间:22.91295337677002秒
程序运行时间:22.91295337677002秒
程序运行时间:22.91395354270935秒
程序运行时间:22.91395354270935秒
程序运行时间:22.91495394706726秒
程序运行时间:22.91495394706726秒
程序运行时间:22.91495394706726秒
程序运行时间:22.915954113006592秒
程序运行时间:22.915954113006592秒
程序运行时间:22.91696000099182秒
程序运行时间:22.91696000099182秒
程序运行时间:22.91696000099182秒
程序运行时间:22.917954444885254秒
程序运行时间:22.918954849243164秒
程序运行时间:22.919955253601074秒
程序运行时间:22.920960664749146秒
程序运行时间:22.920960664749146秒
程序运行时间:22.92194938659668秒
程序运行时间:22.92194938659668秒
程序运行时间:22.922955751419067秒
程序运行时间:22.922955751419067秒
程序运行时间:22.92396116256714秒
程序运行时间:22.92396116256714秒
程序运行时间:22.924961805343628秒
程序运行时间:22.92595624923706秒
程序运行时间:22.92595624923706秒
程序运行时间:22.92695641517639秒
程序运行时间:22.92695641517639秒
程序运行时间:22.9279625415802秒
程序运行时间:22.9279625415802秒
程序运行时间:22.928962469100952秒
程序运行时间:22.928962469100952秒
程序运行时间:22.929957151412964秒
程序运行时间:22.929957151412964秒
程序运行时间:22.930957555770874秒
程序运行时间:22.930957555770874秒
程序运行时间:22.931957721710205秒
程序运行时间:22.932963609695435秒
程序运行时间:22.933963775634766秒
程序运行时间:22.934963703155518秒
程序运行时间:22.934963703155518秒
程序运行时间:22.935964107513428秒
程序运行时间:22.935964107513428秒
程序运行时间:22.93696427345276秒
程序运行时间:22.93696427345276秒
程序运行时间:22.937952995300293秒
程序运行时间:22.93895936012268秒
程序运行时间:22.939964771270752秒
程序运行时间:22.939964771270752秒
程序运行时间:22.94096541404724秒
程序运行时间:22.94096541404724秒
程序运行时间:22.941959857940674秒
程序运行时间:22.941959857940674秒
程序运行时间:22.943970680236816秒
程序运行时间:22.944966077804565秒
程序运行时间:22.945966243743896秒
程序运行时间:22.945966243743896秒
程序运行时间:22.94695496559143秒
程序运行时间:22.94695496559143秒
程序运行时间:22.94796133041382秒
程序运行时间:22.94796133041382秒
程序运行时间:22.94896149635315秒
程序运行时间:22.94996166229248秒
程序运行时间:22.94996166229248秒
程序运行时间:22.95096755027771秒
程序运行时间:22.951950311660767秒
程序运行时间:22.951950311660767秒
程序运行时间:22.952962398529053秒
程序运行时间:22.952962398529053秒
程序运行时间:22.953956604003906秒
程序运行时间:22.953956604003906秒
程序运行时间:22.954962968826294秒
程序运行时间:22.954962968826294秒
程序运行时间:22.955963134765625秒
程序运行时间:22.955963134765625秒
程序运行时间:22.956963300704956秒
程序运行时间:22.956963300704956秒
程序运行时间:22.957963466644287秒
程序运行时间:22.957963466644287秒
程序运行时间:22.958963871002197秒
程序运行时间:22.958963871002197秒
程序运行时间:22.959964275360107秒
程序运行时间:22.959964275360107秒
程序运行时间:22.96096420288086秒
程序运行时间:22.96096420288086秒
程序运行时间:22.96196436882019秒
程序运行时间:22.96196436882019秒
程序运行时间:22.96297001838684秒
程序运行时间:22.96297001838684秒
程序运行时间:22.96396493911743秒
程序运行时间:22.96396493911743秒
程序运行时间:22.964970350265503秒
程序运行时间:22.964970350265503秒
程序运行时间:22.965965270996094秒
程序运行时间:22.965965270996094秒
程序运行时间:22.966965436935425秒
程序运行时间:22.966965436935425秒
程序运行时间:22.967971324920654秒
程序运行时间:22.968966007232666秒
程序运行时间:22.969971656799316秒
程序运行时间:22.970971822738647秒
程序运行时间:22.970971822738647秒
程序运行时间:22.97296690940857秒
程序运行时间:22.97397255897522秒
程序运行时间:22.97397255897522秒
程序运行时间:22.97497296333313秒
程序运行时间:22.97497296333313秒
程序运行时间:22.975967407226562秒
程序运行时间:22.975967407226562秒
程序运行时间:22.976967811584473秒
程序运行时间:22.976967811584473秒
程序运行时间:22.977967977523804秒
程序运行时间:22.977967977523804秒
程序运行时间:22.978968143463135秒
程序运行时间:22.978968143463135秒
程序运行时间:22.979968547821045秒
程序运行时间:22.979968547821045秒
程序运行时间:22.980974197387695秒
程序运行时间:22.980974197387695秒
程序运行时间:22.981968879699707秒
程序运行时间:22.981968879699707秒
程序运行时间:22.982969045639038秒
程序运行时间:22.982969045639038秒
程序运行时间:22.98396944999695秒
程序运行时间:22.98396944999695秒
程序运行时间:22.984963417053223秒
程序运行时间:22.98596978187561秒
程序运行时间:22.98596978187561秒
程序运行时间:22.98697018623352秒
程序运行时间:22.98697018623352秒
程序运行时间:22.98797035217285秒
程序运行时间:22.98797035217285秒
程序运行时间:22.988970518112183秒
程序运行时间:22.988970518112183秒
程序运行时间:22.989970684051514秒
程序运行时间:22.989970684051514秒
程序运行时间:22.990971088409424秒
程序运行时间:22.990971088409424秒
程序运行时间:22.991971015930176秒
程序运行时间:22.991971015930176秒
程序运行时间:22.992971897125244秒
程序运行时间:22.992971897125244秒
程序运行时间:22.993971586227417秒
程序运行时间:22.993971586227417秒
程序运行时间:22.994971752166748秒
程序运行时间:22.994971752166748秒
程序运行时间:22.99597191810608秒
程序运行时间:22.99597191810608秒
程序运行时间:22.99697232246399秒
程序运行时间:22.99697232246399秒
程序运行时间:22.99797248840332秒
程序运行时间:22.99797248840332秒
程序运行时间:22.99897289276123秒
程序运行时间:22.99897289276123秒
程序运行时间:22.99997305870056秒
程序运行时间:22.99997305870056秒
程序运行时间:23.000973224639893秒
程序运行时间:23.000973224639893秒
程序运行时间:23.001973390579224秒
程序运行时间:23.001973390579224秒
程序运行时间:23.002973556518555秒
程序运行时间:23.002973556518555秒
程序运行时间:23.003973722457886秒
程序运行时间:23.003973722457886秒
程序运行时间:23.004974126815796秒
程序运行时间:23.004974126815796秒
程序运行时间:23.005979776382446秒
程序运行时间:23.005979776382446秒
程序运行时间:23.006974697113037秒
程序运行时间:23.006974697113037秒
程序运行时间:23.007975101470947秒
程序运行时间:23.008965492248535秒
程序运行时间:23.009963274002075秒
程序运行时间:23.01096272468567秒
程序运行时间:23.01096272468567秒
程序运行时间:23.011962890625秒
程序运行时间:23.011962890625秒
程序运行时间:23.01296305656433秒
程序运行时间:23.01296305656433秒
程序运行时间:23.01396346092224秒
程序运行时间:23.01396346092224秒
程序运行时间:23.014963388442993秒
程序运行时间:23.014963388442993秒
程序运行时间:23.015963554382324秒
程序运行时间:23.015963554382324秒
程序运行时间:23.016963720321655秒
程序运行时间:23.016963720321655秒
程序运行时间:23.017963886260986秒
程序运行时间:23.017963886260986秒
程序运行时间:23.018964052200317秒
程序运行时间:23.018964052200317秒
程序运行时间:23.019964456558228秒
程序运行时间:23.019964456558228秒
程序运行时间:23.020964860916138秒
程序运行时间:23.020964860916138秒
程序运行时间:23.02196478843689秒
程序运行时间:23.02196478843689秒
程序运行时间:23.0229651927948秒
程序运行时间:23.0229651927948秒
程序运行时间:23.02396535873413秒
程序运行时间:23.02396535873413秒
程序运行时间:23.024965524673462秒
程序运行时间:23.024965524673462秒
程序运行时间:23.025965690612793秒
程序运行时间:23.025965690612793秒
程序运行时间:23.026965856552124秒
程序运行时间:23.026965856552124秒
程序运行时间:23.027966499328613秒
程序运行时间:23.027966499328613秒
程序运行时间:23.028966426849365秒
程序运行时间:23.029974937438965秒
程序运行时间:23.029974937438965秒
程序运行时间:23.03097438812256秒
程序运行时间:23.03097438812256秒
程序运行时间:23.03197431564331秒
程序运行时间:23.03197431564331秒
程序运行时间:23.03197431564331秒
程序运行时间:23.033096313476562秒
程序运行时间:23.033096313476562秒
程序运行时间:23.03398084640503秒
程序运行时间:23.03398084640503秒
程序运行时间:23.03498101234436秒
程序运行时间:23.03498101234436秒
程序运行时间:23.03498101234436秒
程序运行时间:23.035975456237793秒
程序运行时间:23.035975456237793秒
程序运行时间:23.035975456237793秒
程序运行时间:23.037172555923462秒
程序运行时间:23.037172555923462秒
程序运行时间:23.037981748580933秒
程序运行时间:23.037981748580933秒
程序运行时间:23.039032697677612秒
程序运行时间:23.039032697677612秒
程序运行时间:23.039982318878174秒
程序运行时间:23.039982318878174秒
程序运行时间:23.039982318878174秒
程序运行时间:23.040982484817505秒
程序运行时间:23.040982484817505秒
程序运行时间:23.041982412338257秒
程序运行时间:23.041982412338257秒
程序运行时间:23.042982578277588秒
程序运行时间:23.042982578277588秒
程序运行时间:23.043982982635498秒
程序运行时间:23.043982982635498秒
程序运行时间:23.043982982635498秒
程序运行时间:23.04498291015625秒
程序运行时间:23.045971155166626秒
程序运行时间:23.045971155166626秒
程序运行时间:23.046979427337646秒
程序运行时间:23.046979427337646秒
程序运行时间:23.047977924346924秒
程序运行时间:23.047977924346924秒
程序运行时间:23.04898428916931秒
程序运行时间:23.04898428916931秒
程序运行时间:23.049984455108643秒
程序运行时间:23.049984455108643秒
程序运行时间:23.050984621047974秒
程序运行时间:23.050984621047974秒
程序运行时间:23.051984786987305秒
程序运行时间:23.052984952926636秒
程序运行时间:23.052984952926636秒
程序运行时间:23.052984952926636秒
程序运行时间:23.053985118865967秒
程序运行时间:23.053985118865967秒
程序运行时间:23.053985118865967秒
程序运行时间:23.054985523223877秒
程序运行时间:23.054985523223877秒
程序运行时间:23.055985927581787秒
程序运行时间:23.055985927581787秒
程序运行时间:23.055985927581787秒
程序运行时间:23.05698585510254秒
程序运行时间:23.05698585510254秒
程序运行时间:23.05798602104187秒
程序运行时间:23.05798602104187秒
程序运行时间:23.05798602104187秒
程序运行时间:23.0589861869812秒
程序运行时间:23.0589861869812秒
程序运行时间:23.059986352920532秒
程序运行时间:23.059986352920532秒
程序运行时间:23.059986352920532秒
程序运行时间:23.0609872341156秒
程序运行时间:23.0609872341156秒
程序运行时间:23.061980962753296秒
程序运行时间:23.061980962753296秒
程序运行时间:23.061980962753296秒
程序运行时间:23.062981128692627秒
程序运行时间:23.062981128692627秒
程序运行时间:23.062981128692627秒
程序运行时间:23.063987493515015秒
程序运行时间:23.063987493515015秒
程序运行时间:23.064987659454346秒
程序运行时间:23.064987659454346秒
程序运行时间:23.064987659454346秒
程序运行时间:23.065987825393677秒
程序运行时间:23.065987825393677秒
程序运行时间:23.066987991333008秒
程序运行时间:23.066987991333008秒
程序运行时间:23.066987991333008秒
程序运行时间:23.06798815727234秒
程序运行时间:23.06798815727234秒
程序运行时间:23.06898832321167秒
程序运行时间:23.06898832321167秒
程序运行时间:23.06898832321167秒
程序运行时间:23.069988489151秒
程序运行时间:23.069988489151秒
程序运行时间:23.069988489151秒
程序运行时间:23.07098889350891秒
程序运行时间:23.07098889350891秒
程序运行时间:23.07198929786682秒
程序运行时间:23.07198929786682秒
程序运行时间:23.07198929786682秒
程序运行时间:23.072989463806152秒
程序运行时间:23.072989463806152秒
程序运行时间:23.073989629745483秒
程序运行时间:23.073989629745483秒
程序运行时间:23.073989629745483秒
程序运行时间:23.074989795684814秒
程序运行时间:23.075989961624146秒
程序运行时间:23.075989961624146秒
程序运行时间:23.076990365982056秒
程序运行时间:23.076990365982056秒
程序运行时间:23.077990531921387秒
程序运行时间:23.077990531921387秒
程序运行时间:23.077990531921387秒
程序运行时间:23.078977823257446秒
程序运行时间:23.078977823257446秒
程序运行时间:23.07998514175415秒
程序运行时间:23.07998514175415秒
程序运行时间:23.07998514175415秒
程序运行时间:23.08098530769348秒
程序运行时间:23.08098530769348秒
程序运行时间:23.08098530769348秒
程序运行时间:23.08199143409729秒
程序运行时间:23.08199143409729秒
程序运行时间:23.0829918384552秒
程序运行时间:23.0829918384552秒
程序运行时间:23.0829918384552秒
程序运行时间:23.083991765975952秒
程序运行时间:23.083991765975952秒
程序运行时间:23.08499240875244秒
程序运行时间:23.08499240875244秒
程序运行时间:23.08499240875244秒
程序运行时间:23.085992097854614秒
程序运行时间:23.085992097854614秒
程序运行时间:23.085992097854614秒
程序运行时间:23.086992263793945秒
程序运行时间:23.086992263793945秒
程序运行时间:23.087992668151855秒
程序运行时间:23.087992668151855秒
程序运行时间:23.087992668151855秒
程序运行时间:23.088992595672607秒
程序运行时间:23.088992595672607秒
程序运行时间:23.089993238449097秒
程序运行时间:23.089993238449097秒
程序运行时间:23.089993238449097秒
程序运行时间:23.090993404388428秒
程序运行时间:23.090993404388428秒
程序运行时间:23.09199357032776秒
程序运行时间:23.09199357032776秒
程序运行时间:23.09298825263977秒
程序运行时间:23.09298825263977秒
程序运行时间:23.09298825263977秒
程序运行时间:23.093987941741943秒
程序运行时间:23.093987941741943秒
程序运行时间:23.09499454498291秒
程序运行时间:23.09499454498291秒
程序运行时间:23.09499454498291秒
程序运行时间:23.09598183631897秒
程序运行时间:23.09598183631897秒
程序运行时间:23.096988916397095秒
程序运行时间:23.096988916397095秒
程序运行时间:23.096988916397095秒
程序运行时间:23.097989082336426秒
程序运行时间:23.097989082336426秒
程序运行时间:23.097989082336426秒
程序运行时间:23.098995208740234秒
程序运行时间:23.098995208740234秒
程序运行时间:23.099995374679565秒
程序运行时间:23.099995374679565秒
程序运行时间:23.099995374679565秒
程序运行时间:23.100995779037476秒
程序运行时间:23.100995779037476秒
程序运行时间:23.101995944976807秒
程序运行时间:23.101995944976807秒
程序运行时间:23.102996110916138秒
程序运行时间:23.102996110916138秒
程序运行时间:23.10399627685547秒
程序运行时间:23.10399627685547秒
程序运行时间:23.10399627685547秒
程序运行时间:23.1049964427948秒
程序运行时间:23.1049964427948秒
程序运行时间:23.1049964427948秒
程序运行时间:23.10599684715271秒
程序运行时间:23.10599684715271秒
程序运行时间:23.10699701309204秒
程序运行时间:23.107985496520996秒
程序运行时间:23.107985496520996秒
程序运行时间:23.10898470878601秒
程序运行时间:23.10898470878601秒
程序运行时间:23.10898470878601秒
程序运行时间:23.109985828399658秒
程序运行时间:23.109985828399658秒
程序运行时间:23.110985040664673秒
程序运行时间:23.110985040664673秒
程序运行时间:23.111985683441162秒
程序运行时间:23.111985683441162秒
程序运行时间:23.112986087799072秒
程序运行时间:23.113986015319824秒
程序运行时间:23.113986015319824秒
程序运行时间:23.113986015319824秒
程序运行时间:23.114986181259155秒
程序运行时间:23.114986181259155秒
程序运行时间:23.115986347198486秒
程序运行时间:23.115986347198486秒
程序运行时间:23.116986513137817秒
程序运行时间:23.11798667907715秒
程序运行时间:23.11798667907715秒
程序运行时间:23.11898684501648秒
程序运行时间:23.11898684501648秒
程序运行时间:23.11998748779297秒
程序运行时间:23.1209979057312秒
程序运行时间:23.1209979057312秒
程序运行时间:23.121994972229004秒
程序运行时间:23.121994972229004秒
程序运行时间:23.122995138168335秒
程序运行时间:23.122995138168335秒
程序运行时间:23.123998165130615秒
程序运行时间:23.123998165130615秒
程序运行时间:23.123998165130615秒
程序运行时间:23.124995470046997秒
程序运行时间:23.124995470046997秒
程序运行时间:23.12600588798523秒
程序运行时间:23.12600588798523秒
程序运行时间:23.12600588798523秒
程序运行时间:23.127001523971558秒
程序运行时间:23.127001523971558秒
程序运行时间:23.128021240234375秒
程序运行时间:23.128021240234375秒
程序运行时间:23.128021240234375秒
程序运行时间:23.12898826599121秒
程序运行时间:23.12999701499939秒
程序运行时间:23.12999701499939秒
程序运行时间:23.130996465682983秒
程序运行时间:23.130996465682983秒
程序运行时间:23.130996465682983秒
程序运行时间:23.1321120262146秒
程序运行时间:23.1321120262146秒
程序运行时间:23.133002996444702秒
程序运行时间:23.133002996444702秒
程序运行时间:23.133002996444702秒
程序运行时间:23.134193181991577秒
程序运行时间:23.134193181991577秒
程序运行时间:23.135003089904785秒
程序运行时间:23.135003089904785秒
程序运行时间:23.136009216308594秒
程序运行时间:23.136009216308594秒
程序运行时间:23.136009216308594秒
程序运行时间:23.137003898620605秒
程序运行时间:23.137003898620605秒
程序运行时间:23.137003898620605秒
程序运行时间:23.13801383972168秒
程序运行时间:23.13801383972168秒
程序运行时间:23.139004468917847秒
程序运行时间:23.139004468917847秒
程序运行时间:23.139999628067017秒
程序运行时间:23.139999628067017秒
程序运行时间:23.139999628067017秒
程序运行时间:23.140998601913452秒
程序运行时间:23.140998601913452秒
程序运行时间:23.140998601913452秒
程序运行时间:23.142019987106323秒
程序运行时间:23.142019987106323秒
程序运行时间:23.143004894256592秒
程序运行时间:23.14400553703308秒
程序运行时间:23.145005464553833秒
程序运行时间:23.145005464553833秒
程序运行时间:23.146005630493164秒
程序运行时间:23.146005630493164秒
程序运行时间:23.146005630493164秒
程序运行时间:23.147006034851074秒
程序运行时间:23.147006034851074秒
程序运行时间:23.148008584976196秒
程序运行时间:23.148008584976196秒
程序运行时间:23.148008584976196秒
程序运行时间:23.149006605148315秒
程序运行时间:23.149006605148315秒
程序运行时间:23.15002727508545秒
程序运行时间:23.15002727508545秒
程序运行时间:23.15002727508545秒
程序运行时间:23.151006937026978秒
程序运行时间:23.151006937026978秒
程序运行时间:23.151006937026978秒
程序运行时间:23.1520357131958秒
程序运行时间:23.1520357131958秒
程序运行时间:23.15300726890564秒
程序运行时间:23.15300726890564秒
程序运行时间:23.15300726890564秒
程序运行时间:23.15400767326355秒
程序运行时间:23.15400767326355秒
程序运行时间:23.1550076007843秒
程序运行时间:23.1550076007843秒
程序运行时间:23.1550076007843秒
程序运行时间:23.15600872039795秒
程序运行时间:23.15600872039795秒
程序运行时间:23.157002925872803秒
程序运行时间:23.157002925872803秒
程序运行时间:23.157002925872803秒
程序运行时间:23.158008813858032秒
程序运行时间:23.158008813858032秒
程序运行时间:23.159009218215942秒
程序运行时间:23.159009218215942秒
程序运行时间:23.159009218215942秒
程序运行时间:23.160009384155273秒
程序运行时间:23.160009384155273秒
程序运行时间:23.161009550094604秒
程序运行时间:23.161009550094604秒
程序运行时间:23.161009550094604秒
程序运行时间:23.162009239196777秒
程序运行时间:23.162009239196777秒
程序运行时间:23.163009643554688秒
程序运行时间:23.163009643554688秒
程序运行时间:23.163009643554688秒
程序运行时间:23.16400980949402秒
程序运行时间:23.16400980949402秒
程序运行时间:23.16400980949402秒
程序运行时间:23.16503143310547秒
程序运行时间:23.16503143310547秒
程序运行时间:23.16601014137268秒
程序运行时间:23.16601014137268秒
程序运行时间:23.16601014137268秒
程序运行时间:23.16701054573059秒
程序运行时间:23.16701054573059秒
程序运行时间:23.168010711669922秒
程序运行时间:23.168010711669922秒

程序运行时间:23.643105506896973秒
程序运行时间:23.644105434417725秒
程序运行时间:23.64510464668274秒
程序运行时间:23.64510464668274秒
程序运行时间:23.64610505104065秒
程序运行时间:23.64610505104065秒
程序运行时间:23.64710521697998秒
程序运行时间:23.64710521697998秒
程序运行时间:23.64810538291931秒
程序运行时间:23.64810538291931秒
程序运行时间:23.64910578727722秒
程序运行时间:23.64910578727722秒
程序运行时间:23.650105714797974秒
程序运行时间:23.650105714797974秒
程序运行时间:23.651105880737305秒
程序运行时间:23.651105880737305秒
程序运行时间:23.652106285095215秒
程序运行时间:23.652106285095215秒
程序运行时间:23.653106689453125秒
程序运行时间:23.653106689453125秒
程序运行时间:23.654106855392456秒
程序运行时间:23.654106855392456秒
程序运行时间:23.655107021331787秒
程序运行时间:23.655107021331787秒
程序运行时间:23.656107187271118秒
程序运行时间:23.656107187271118秒
程序运行时间:23.65710735321045秒
程序运行时间:23.65710735321045秒
程序运行时间:23.65810751914978秒
程序运行时间:23.65810751914978秒
程序运行时间:23.659116506576538秒
程序运行时间:23.659116506576538秒
程序运行时间:23.660115242004395秒
程序运行时间:23.660115242004395秒
程序运行时间:23.660115242004395秒
程序运行时间:23.661121368408203秒
程序运行时间:23.661121368408203秒
程序运行时间:23.662122011184692秒
程序运行时间:23.662122011184692秒
程序运行时间:23.663121938705444秒
程序运行时间:23.663121938705444秒
程序运行时间:23.664122343063354秒
程序运行时间:23.664122343063354秒
程序运行时间:23.664122343063354秒
程序运行时间:23.665122270584106秒
程序运行时间:23.665122270584106秒
程序运行时间:23.666135787963867秒
程序运行时间:23.666135787963867秒
程序运行时间:23.666135787963867秒
程序运行时间:23.66712260246277秒
程序运行时间:23.66712260246277秒
程序运行时间:23.668151140213013秒
程序运行时间:23.668151140213013秒
程序运行时间:23.668151140213013秒
程序运行时间:23.66912317276001秒
程序运行时间:23.66912317276001秒
程序运行时间:23.66912317276001秒
程序运行时间:23.670145750045776秒
程序运行时间:23.670145750045776秒
程序运行时间:23.67112374305725秒
程序运行时间:23.67112374305725秒
程序运行时间:23.67112374305725秒
程序运行时间:23.672123670578003秒
程序运行时间:23.672123670578003秒
程序运行时间:23.673124074935913秒
程序运行时间:23.673124074935913秒
程序运行时间:23.673124074935913秒
程序运行时间:23.674314260482788秒
程序运行时间:23.675124883651733秒
程序运行时间:23.675124883651733秒
程序运行时间:23.675124883651733秒
程序运行时间:23.676124572753906秒
程序运行时间:23.676124572753906秒
程序运行时间:23.677141666412354秒
程序运行时间:23.677141666412354秒
程序运行时间:23.677141666412354秒
程序运行时间:23.67812490463257秒
程序运行时间:23.67812490463257秒
程序运行时间:23.679125547409058秒
程序运行时间:23.679125547409058秒
程序运行时间:23.679125547409058秒
程序运行时间:23.68012571334839秒
程序运行时间:23.68012571334839秒
程序运行时间:23.68012571334839秒
程序运行时间:23.68113923072815秒
程序运行时间:23.68113923072815秒
程序运行时间:23.68212628364563秒
程序运行时间:23.68312668800354秒
程序运行时间:23.68312668800354秒
程序运行时间:23.684126377105713秒
程序运行时间:23.684126377105713秒
程序运行时间:23.684126377105713秒
程序运行时间:23.685316562652588秒
程序运行时间:23.685316562652588秒
程序运行时间:23.686126947402954秒
程序运行时间:23.686126947402954秒
程序运行时间:23.687240839004517秒
程序运行时间:23.687240839004517秒
程序运行时间:23.688127517700195秒
程序运行时间:23.688127517700195秒
程序运行时间:23.68913197517395秒
程序运行时间:23.68913197517395秒
程序运行时间:23.68913197517395秒
程序运行时间:23.690127849578857秒
程序运行时间:23.690127849578857秒
程序运行时间:23.691145181655884秒
程序运行时间:23.691145181655884秒
程序运行时间:23.69212818145752秒
程序运行时间:23.69212818145752秒
程序运行时间:23.69212818145752秒
程序运行时间:23.69323468208313秒
程序运行时间:23.69323468208313秒
程序运行时间:23.69412875175476秒
程序运行时间:23.69412875175476秒
程序运行时间:23.695128917694092秒
程序运行时间:23.696128845214844秒
程序运行时间:23.696128845214844秒
程序运行时间:23.697129726409912秒
程序运行时间:23.697129726409912秒
程序运行时间:23.697129726409912秒
程序运行时间:23.698129653930664秒
程序运行时间:23.698129653930664秒
程序运行时间:23.698129653930664秒
程序运行时间:23.6993191242218秒
程序运行时间:23.6993191242218秒
程序运行时间:23.700130224227905秒
程序运行时间:23.700130224227905秒
程序运行时间:23.701130390167236秒
程序运行时间:23.701130390167236秒
程序运行时间:23.701130390167236秒
程序运行时间:23.70213031768799秒
程序运行时间:23.70213031768799秒
程序运行时间:23.70213031768799秒
程序运行时间:23.70313048362732秒
程序运行时间:23.70313048362732秒
程序运行时间:23.70413112640381秒
程序运行时间:23.70513129234314秒
程序运行时间:23.70513129234314秒
程序运行时间:23.706125497817993秒
程序运行时间:23.706125497817993秒
程序运行时间:23.7071316242218秒
程序运行时间:23.7071316242218秒
程序运行时间:23.7071316242218秒
程序运行时间:23.708131790161133秒
程序运行时间:23.708131790161133秒
程序运行时间:23.709131956100464秒
程序运行时间:23.709131956100464秒
程序运行时间:23.709131956100464秒
程序运行时间:23.710132360458374秒
程序运行时间:23.710132360458374秒
程序运行时间:23.710132360458374秒
程序运行时间:23.711132287979126秒
程序运行时间:23.711132287979126秒
程序运行时间:23.712132692337036秒
程序运行时间:23.712132692337036秒
程序运行时间:23.712132692337036秒
程序运行时间:23.713120222091675秒
程序运行时间:23.713120222091675秒
程序运行时间:23.71412706375122秒
程序运行时间:23.71412706375122秒
程序运行时间:23.71412706375122秒
程序运行时间:23.71512746810913秒
程序运行时间:23.71512746810913秒
程序运行时间:23.71512746810913秒
程序运行时间:23.71613359451294秒
程序运行时间:23.71613359451294秒
程序运行时间:23.71713376045227秒
程序运行时间:23.71713376045227秒
程序运行时间:23.71713376045227秒
程序运行时间:23.7181339263916秒
程序运行时间:23.7181339263916秒
程序运行时间:23.719134092330933秒
程序运行时间:23.719134092330933秒
程序运行时间:23.719134092330933秒
程序运行时间:23.726531267166138秒
程序运行时间:23.72854733467102秒
程序运行时间:23.72854733467102秒
程序运行时间:23.729547262191772秒
程序运行时间:23.729547262191772秒
程序运行时间:23.730547666549683秒
程序运行时间:23.730547666549683秒
程序运行时间:23.731547594070435秒
程序运行时间:23.731547594070435秒
程序运行时间:23.732547998428345秒
程序运行时间:23.732547998428345秒
程序运行时间:23.733548164367676秒
程序运行时间:23.733548164367676秒
程序运行时间:23.73456382751465秒
程序运行时间:23.735549211502075秒
程序运行时间:23.735549211502075秒
程序运行时间:23.736549854278564秒
程序运行时间:23.736549854278564秒
程序运行时间:23.7375431060791秒
程序运行时间:23.7375431060791秒
程序运行时间:23.73854947090149秒
程序运行时间:23.73854947090149秒
程序运行时间:23.73954963684082秒
程序运行时间:23.73954963684082秒
程序运行时间:23.74054980278015秒
程序运行时间:23.74054980278015秒
程序运行时间:23.741549968719482秒
程序运行时间:23.741549968719482秒
程序运行时间:23.742550134658813秒
程序运行时间:23.742550134658813秒
程序运行时间:23.743550300598145秒
程序运行时间:23.743550300598145秒
程序运行时间:23.744550704956055秒
程序运行时间:23.744550704956055秒
程序运行时间:23.745550870895386秒
程序运行时间:23.745550870895386秒
程序运行时间:23.746551036834717秒
程序运行时间:23.747552394866943秒
程序运行时间:23.747552394866943秒
程序运行时间:23.748557567596436秒
程序运行时间:23.748557567596436秒
程序运行时间:23.749595403671265秒
程序运行时间:23.7505521774292秒
程序运行时间:23.7505521774292秒
程序运行时间:23.75155282020569秒
程序运行时间:23.75155282020569秒
程序运行时间:23.7525532245636秒
程序运行时间:23.7525532245636秒
程序运行时间:23.753546714782715秒
程序运行时间:23.753546714782715秒
程序运行时间:23.754553079605103秒
程序运行时间:23.754553079605103秒
程序运行时间:23.755553245544434秒
程序运行时间:23.755553245544434秒
程序运行时间:23.756553411483765秒
程序运行时间:23.756553411483765秒
程序运行时间:23.757553577423096秒
程序运行时间:23.757553577423096秒
程序运行时间:23.758553743362427秒
程序运行时间:23.759553909301758秒
程序运行时间:23.759553909301758秒
程序运行时间:23.76055407524109秒
程序运行时间:23.76055407524109秒
程序运行时间:23.761554718017578秒
程序运行时间:23.761554718017578秒
程序运行时间:23.76255488395691秒
程序运行时间:23.76255488395691秒
程序运行时间:23.76355481147766秒
程序运行时间:23.76355481147766秒
程序运行时间:23.76455569267273秒
程序运行时间:23.76455569267273秒
程序运行时间:23.76555562019348秒
程序运行时间:23.76555562019348秒
程序运行时间:23.766555786132812秒
程序运行时间:23.766555786132812秒
程序运行时间:23.767555475234985秒
程序运行时间:23.767555475234985秒
程序运行时间:23.768556118011475秒
程序运行时间:23.768556118011475秒
程序运行时间:23.769556045532227秒
程序运行时间:23.769556045532227秒
程序运行时间:23.770556688308716秒
程序运行时间:23.770556688308716秒
程序运行时间:23.771556854248047秒
程序运行时间:23.771556854248047秒
程序运行时间:23.772557258605957秒
程序运行时间:23.772557258605957秒
程序运行时间:23.77355718612671秒
程序运行时间:23.77355718612671秒
程序运行时间:23.77455735206604秒
程序运行时间:23.77455735206604秒
程序运行时间:23.77555751800537秒
程序运行时间:23.77555751800537秒
程序运行时间:23.776557683944702秒
程序运行时间:23.776557683944702秒
程序运行时间:23.777557849884033秒
程序运行时间:23.777557849884033秒
程序运行时间:23.778558492660522秒
程序运行时间:23.778558492660522秒
程序运行时间:23.779558658599854秒
程序运行时间:23.78056001663208秒
程序运行时间:23.78056001663208秒
程序运行时间:23.78156018257141秒
程序运行时间:23.78156018257141秒
程序运行时间:23.78255534172058秒
程序运行时间:23.78255534172058秒
程序运行时间:23.783559799194336秒
程序运行时间:23.783559799194336秒
程序运行时间:23.78455400466919秒
程序运行时间:23.78455400466919秒
程序运行时间:23.78555989265442秒
程序运行时间:23.78555989265442秒
程序运行时间:23.786560535430908秒
程序运行时间:23.786560535430908秒
程序运行时间:23.78756070137024秒
程序运行时间:23.78756070137024秒
程序运行时间:23.78856062889099秒
程序运行时间:23.78856062889099秒
程序运行时间:23.7895610332489秒
程序运行时间:23.7895610332489秒
程序运行时间:23.790560960769653秒
程序运行时间:23.790560960769653秒
程序运行时间:23.791561126708984秒
程序运行时间:23.791561126708984秒
程序运行时间:23.792561769485474秒
程序运行时间:23.792561769485474秒
程序运行时间:23.793561697006226秒
程序运行时间:23.793561697006226秒
程序运行时间:23.794562101364136秒
程序运行时间:23.794562101364136秒
程序运行时间:23.795562267303467秒
程序运行时间:23.795562267303467秒
程序运行时间:23.796562433242798秒
程序运行时间:23.796562433242798秒
程序运行时间:23.797562837600708秒
程序运行时间:23.79856300354004秒
程序运行时间:23.799551010131836秒
程序运行时间:23.799551010131836秒
程序运行时间:23.799551010131836秒
程序运行时间:23.800563097000122秒
程序运行时间:23.800563097000122秒
程序运行时间:23.800563097000122秒
程序运行时间:23.80155110359192秒
程序运行时间:23.802557706832886秒
程序运行时间:23.803553104400635秒
程序运行时间:23.803553104400635秒
程序运行时间:23.803553104400635秒
程序运行时间:23.804558992385864秒
程序运行时间:23.805565357208252秒
程序运行时间:23.805565357208252秒
程序运行时间:23.806565523147583秒
程序运行时间:23.806565523147583秒
程序运行时间:23.807565212249756秒
程序运行时间:23.807565212249756秒
程序运行时间:23.807565212249756秒
程序运行时间:23.808565378189087秒
程序运行时间:23.809566259384155秒
程序运行时间:23.809566259384155秒
程序运行时间:23.810582160949707秒
程序运行时间:23.811566591262817秒
程序运行时间:23.811566591262817秒
程序运行时间:23.811566591262817秒
程序运行时间:23.81260657310486秒
程序运行时间:23.81260657310486秒
程序运行时间:23.813566207885742秒
程序运行时间:23.813566207885742秒
程序运行时间:23.81456232070923秒
程序运行时间:23.81456232070923秒
程序运行时间:23.81456232070923秒
程序运行时间:23.815567016601562秒
程序运行时间:23.815567016601562秒
程序运行时间:23.81656765937805秒
程序运行时间:23.81656765937805秒
程序运行时间:23.817567348480225秒
程序运行时间:23.817567348480225秒
程序运行时间:23.817567348480225秒
程序运行时间:23.818654537200928秒
程序运行时间:23.819568157196045秒
程序运行时间:23.819568157196045秒
程序运行时间:23.82056999206543秒
程序运行时间:23.82056999206543秒
程序运行时间:23.82056999206543秒
程序运行时间:23.821568250656128秒
程序运行时间:23.821568250656128秒
程序运行时间:23.822570323944092秒
程序运行时间:23.822570323944092秒
程序运行时间:23.822570323944092秒
程序运行时间:23.82356882095337秒
程序运行时间:23.82356882095337秒
程序运行时间:23.82356882095337秒
程序运行时间:23.8245689868927秒
程序运行时间:23.82556939125061秒
程序运行时间:23.82556939125061秒
程序运行时间:23.8265700340271秒
程序运行时间:23.8265700340271秒
程序运行时间:23.82756996154785秒
程序运行时间:23.82756996154785秒
程序运行时间:23.82756996154785秒
程序运行时间:23.8286030292511秒
程序运行时间:23.8286030292511秒
程序运行时间:23.829569816589355秒
程序运行时间:23.829569816589355秒
程序运行时间:23.83055853843689秒
程序运行时间:23.83055853843689秒
程序运行时间:23.831567525863647秒
程序运行时间:23.831567525863647秒
程序运行时间:23.832767248153687秒
程序运行时间:23.832767248153687秒
程序运行时间:23.833570957183838秒
程序运行时间:23.833570957183838秒
程序运行时间:23.834577083587646秒
程序运行时间:23.834577083587646秒
程序运行时间:23.834577083587646秒
程序运行时间:23.8355712890625秒
程序运行时间:23.8355712890625秒
程序运行时间:23.836571216583252秒
程序运行时间:23.836571216583252秒
程序运行时间:23.836571216583252秒
程序运行时间:23.8375723361969秒
程序运行时间:23.8375723361969秒
程序运行时间:23.83859658241272秒
程序运行时间:23.83859658241272秒
程序运行时间:23.83859658241272秒
程序运行时间:23.839572429656982秒
程序运行时间:23.839572429656982秒
程序运行时间:23.839572429656982秒
程序运行时间:23.840643167495728秒
程序运行时间:23.840643167495728秒
程序运行时间:23.841572761535645秒
程序运行时间:23.841572761535645秒
程序运行时间:23.841572761535645秒
程序运行时间:23.842573165893555秒
程序运行时间:23.842573165893555秒
程序运行时间:23.843573331832886秒
程序运行时间:23.843573331832886秒
程序运行时间:23.843573331832886秒
程序运行时间:23.844573974609375秒
程序运行时间:23.844573974609375秒
程序运行时间:23.845573663711548秒
程序运行时间:23.845573663711548秒
程序运行时间:23.846575021743774秒
程序运行时间:23.846575021743774秒
程序运行时间:23.847574472427368秒
程序运行时间:23.847574472427368秒
程序运行时间:23.847574472427368秒
程序运行时间:23.84857416152954秒
程序运行时间:23.84857416152954秒
程序运行时间:23.84857416152954秒
程序运行时间:23.84957480430603秒
程序运行时间:23.84957480430603秒
程序运行时间:23.850574731826782秒
程序运行时间:23.850574731826782秒
程序运行时间:23.850574731826782秒
程序运行时间:23.851574659347534秒
程序运行时间:23.851574659347534秒
程序运行时间:23.852575063705444秒
程序运行时间:23.852575063705444秒
程序运行时间:23.852575063705444秒
程序运行时间:23.853575944900513秒
程序运行时间:23.853575944900513秒
程序运行时间:23.853575944900513秒
程序运行时间:23.854575872421265秒
程序运行时间:23.854575872421265秒
程序运行时间:23.855575799942017秒
程序运行时间:23.855575799942017秒
程序运行时间:23.855575799942017秒
程序运行时间:23.856575965881348秒
程序运行时间:23.856575965881348秒
程序运行时间:23.85757613182068秒
程序运行时间:23.85757613182068秒
程序运行时间:23.85757613182068秒
程序运行时间:23.858577489852905秒
程序运行时间:23.858577489852905秒
程序运行时间:23.8595769405365秒
程序运行时间:23.8595769405365秒
程序运行时间:23.8595769405365秒
程序运行时间:23.86057686805725秒
程序运行时间:23.86057686805725秒
程序运行时间:23.861577033996582秒
程序运行时间:23.862566232681274秒
程序运行时间:23.862566232681274秒
程序运行时间:23.86356520652771秒
程序运行时间:23.864566802978516秒
程序运行时间:23.864566802978516秒
程序运行时间:23.864566802978516秒
程序运行时间:23.86556625366211秒
程序运行时间:23.86556625366211秒
程序运行时间:23.866565227508545秒
程序运行时间:23.866565227508545秒
程序运行时间:23.866565227508545秒
程序运行时间:23.867565393447876秒
程序运行时间:23.867565393447876秒
程序运行时间:23.868565320968628秒
程序运行时间:23.868565320968628秒
程序运行时间:23.868565320968628秒
程序运行时间:23.869565725326538秒
程序运行时间:23.869565725326538秒
程序运行时间:23.870567083358765秒
程序运行时间:23.870567083358765秒
程序运行时间:23.870567083358765秒
程序运行时间:23.871567010879517秒
程序运行时间:23.871567010879517秒
程序运行时间:23.87256646156311秒
程序运行时间:23.87256646156311秒
程序运行时间:23.87256646156311秒
程序运行时间:23.8735671043396秒
程序运行时间:23.8735671043396秒
程序运行时间:23.8735671043396秒
程序运行时间:23.87456703186035秒
程序运行时间:23.87456703186035秒
程序运行时间:23.875567197799683秒
程序运行时间:23.875567197799683秒
程序运行时间:23.876567602157593秒
程序运行时间:23.876567602157593秒
程序运行时间:23.877568006515503秒
程序运行时间:23.877568006515503秒
程序运行时间:23.877568006515503秒
程序运行时间:23.878568649291992秒
程序运行时间:23.878568649291992秒
程序运行时间:23.879568338394165秒
程序运行时间:23.879568338394165秒
程序运行时间:23.879568338394165秒
程序运行时间:23.880568265914917秒
程序运行时间:23.880568265914917秒
程序运行时间:23.881568431854248秒
程序运行时间:23.881568431854248秒
程序运行时间:23.881568431854248秒
程序运行时间:23.882568836212158秒
程序运行时间:23.882568836212158秒
程序运行时间:23.882568836212158秒
程序运行时间:23.88356876373291秒
程序运行时间:23.88356876373291秒
程序运行时间:23.88456964492798秒
程序运行时间:23.88456964492798秒
程序运行时间:23.88456964492798秒
程序运行时间:23.88556957244873秒
程序运行时间:23.88556957244873秒
程序运行时间:23.88656973838806秒
程序运行时间:23.88656973838806秒
程序运行时间:23.88656973838806秒
程序运行时间:23.887571096420288秒
程序运行时间:23.887571096420288秒
程序运行时间:23.888570070266724秒
程序运行时间:23.888570070266724秒
程序运行时间:23.888570070266724秒
程序运行时间:23.889570713043213秒
程序运行时间:23.889570713043213秒
程序运行时间:23.890570640563965秒
程序运行时间:23.890570640563965秒
程序运行时间:23.890570640563965秒
程序运行时间:23.891570568084717秒
程序运行时间:23.891570568084717秒
程序运行时间:23.891570568084717秒
程序运行时间:23.892570972442627秒
程序运行时间:23.892570972442627秒
程序运行时间:23.893571376800537秒
程序运行时间:23.893571376800537秒
程序运行时间:23.893571376800537秒
程序运行时间:23.894572019577026秒
程序运行时间:23.894572019577026秒
程序运行时间:23.8955717086792秒
程序运行时间:23.8955717086792秒
程序运行时间:23.8955717086792秒
程序运行时间:23.89657187461853秒
程序运行时间:23.89757204055786秒
程序运行时间:23.89757204055786秒
程序运行时间:23.89757204055786秒
程序运行时间:23.898572206497192秒
程序运行时间:23.898572206497192秒
程序运行时间:23.899572372436523秒
程序运行时间:23.899572372436523秒
程序运行时间:23.899572372436523秒
程序运行时间:23.900572776794434秒
程序运行时间:23.901573419570923秒
程序运行时间:23.901573419570923秒
程序运行时间:23.901573419570923秒
程序运行时间:23.902573585510254秒
程序运行时间:23.902573585510254秒
程序运行时间:23.902573585510254秒
程序运行时间:23.903573751449585秒
程序运行时间:23.903573751449585秒
程序运行时间:23.904573917388916秒
程序运行时间:23.904573917388916秒
程序运行时间:23.904573917388916秒
程序运行时间:23.905573844909668秒
程序运行时间:23.905573844909668秒
程序运行时间:23.906574249267578秒
程序运行时间:23.906574249267578秒
程序运行时间:23.906574249267578秒
程序运行时间:23.90757417678833秒
程序运行时间:23.90757417678833秒
程序运行时间:23.90857434272766秒
程序运行时间:23.90857434272766秒
程序运行时间:23.90857434272766秒
程序运行时间:23.90957474708557秒
程序运行时间:23.90957474708557秒
程序运行时间:23.91057586669922秒
程序运行时间:23.91057586669922秒
程序运行时间:23.91057586669922秒
程序运行时间:23.91157555580139秒
程序运行时间:23.91157555580139秒
程序运行时间:23.91157555580139秒
程序运行时间:23.912575483322144秒
程序运行时间:23.912575483322144秒
程序运行时间:23.913575887680054秒
程序运行时间:23.913575887680054秒
程序运行时间:23.913575887680054秒
程序运行时间:23.914576053619385秒
程序运行时间:23.914576053619385秒
程序运行时间:23.915576219558716秒
程序运行时间:23.915576219558716秒
程序运行时间:23.915576219558716秒
程序运行时间:23.916576623916626秒
程序运行时间:23.916576623916626秒
程序运行时间:23.917576789855957秒
程序运行时间:23.917576789855957秒
程序运行时间:23.917576789855957秒
程序运行时间:23.918577194213867秒
程序运行时间:23.918577194213867秒
程序运行时间:23.918577194213867秒
程序运行时间:23.91957712173462秒
程序运行时间:23.91957712173462秒
程序运行时间:23.92057752609253秒
程序运行时间:23.92057752609253秒
程序运行时间:23.92057752609253秒
程序运行时间:23.92157793045044秒
程序运行时间:23.92157793045044秒
程序运行时间:23.92257785797119秒
程序运行时间:23.92257785797119秒
程序运行时间:23.92257785797119秒
程序运行时间:23.923578023910522秒
程序运行时间:23.923578023910522秒
程序运行时间:23.924578189849854秒
程序运行时间:23.924578189849854秒
程序运行时间:23.924578189849854秒
程序运行时间:23.925578832626343秒
程序运行时间:23.925578832626343秒
程序运行时间:23.926578521728516秒
程序运行时间:23.926578521728516秒
程序运行时间:23.926578521728516秒
程序运行时间:23.927578926086426秒
程序运行时间:23.927578926086426秒
程序运行时间:23.927578926086426秒
程序运行时间:23.928579330444336秒
程序运行时间:23.928579330444336秒
程序运行时间:23.929579257965088秒
程序运行时间:23.929579257965088秒
程序运行时间:23.929579257965088秒
程序运行时间:23.930580139160156秒
程序运行时间:23.930580139160156秒
程序运行时间:23.93157958984375秒
程序运行时间:23.93157958984375秒
程序运行时间:23.93157958984375秒
程序运行时间:23.93257999420166秒
程序运行时间:23.93257999420166秒
程序运行时间:23.93257999420166秒
程序运行时间:23.93358016014099秒
程序运行时间:23.9345805644989秒
程序运行时间:23.9345805644989秒
程序运行时间:23.9345805644989秒
程序运行时间:23.935580492019653秒
程序运行时间:23.935580492019653秒
程序运行时间:23.93658137321472秒
程序运行时间:23.93658137321472秒
程序运行时间:23.937581300735474秒
程序运行时间:23.937581300735474秒
程序运行时间:23.938581705093384秒
程序运行时间:23.939582109451294秒
程序运行时间:23.939582109451294秒
程序运行时间:23.939582109451294秒
程序运行时间:23.940582275390625秒
程序运行时间:23.940582275390625秒
程序运行时间:23.941582441329956秒
程序运行时间:23.941582441329956秒
程序运行时间:23.94258213043213秒
程序运行时间:23.94258213043213秒
程序运行时间:23.94358229637146秒
程序运行时间:23.94358229637146秒
程序运行时间:23.94358229637146秒
程序运行时间:23.94458293914795秒
程序运行时间:23.94458293914795秒
程序运行时间:23.94558310508728秒
程序运行时间:23.94558310508728秒
程序运行时间:23.94558310508728秒
程序运行时间:23.946584224700928秒
程序运行时间:23.946584224700928秒
程序运行时间:23.947583436965942秒
程序运行时间:23.947583436965942秒
程序运行时间:23.947583436965942秒
程序运行时间:23.94858407974243秒
程序运行时间:23.949583768844604秒
程序运行时间:23.949583768844604秒
程序运行时间:23.950583934783936秒
程序运行时间:23.951584100723267秒
程序运行时间:23.952584743499756秒
程序运行时间:23.952584743499756秒
程序运行时间:23.953585624694824秒
程序运行时间:23.95458674430847秒
程序运行时间:23.95458674430847秒
程序运行时间:23.955585718154907秒
程序运行时间:23.95658588409424秒
程序运行时间:23.95758628845215秒
程序运行时间:23.95758628845215秒
程序运行时间:23.95758628845215秒
程序运行时间:23.958587169647217秒
程序运行时间:23.958587169647217秒
程序运行时间:23.959587574005127秒
程序运行时间:23.959587574005127秒
程序运行时间:23.959587574005127秒
程序运行时间:23.96058702468872秒
程序运行时间:23.96058702468872秒
程序运行时间:23.96158719062805秒
程序运行时间:23.96158719062805秒
程序运行时间:23.962586879730225秒
程序运行时间:23.962586879730225秒
程序运行时间:23.962586879730225秒
程序运行时间:23.963587522506714秒
程序运行时间:23.963587522506714秒
程序运行时间:23.964587926864624秒
程序运行时间:23.964587926864624秒
程序运行时间:23.964587926864624秒
程序运行时间:23.965588092803955秒
程序运行时间:23.965588092803955秒
程序运行时间:23.965588092803955秒
程序运行时间:23.966588258743286秒
程序运行时间:23.966588258743286秒
程序运行时间:23.967589139938354秒
程序运行时间:23.967589139938354秒
程序运行时间:23.967589139938354秒
程序运行时间:23.968588829040527秒
程序运行时间:23.968588829040527秒
程序运行时间:23.96958899497986秒
程序运行时间:23.96958899497986秒
程序运行时间:23.97058916091919秒
程序运行时间:23.97058916091919秒
程序运行时间:23.97158932685852秒
程序运行时间:23.97158932685852秒
程序运行时间:23.97158932685852秒
程序运行时间:23.972590446472168秒
程序运行时间:23.972590446472168秒
程序运行时间:23.972590446472168秒
程序运行时间:23.97358989715576秒
程序运行时间:23.97459053993225秒
程序运行时间:23.97459053993225秒
程序运行时间:23.97459053993225秒
程序运行时间:23.975590229034424秒
程序运行时间:23.975590229034424秒
程序运行时间:23.976590633392334秒
程序运行时间:23.976590633392334秒
程序运行时间:23.977590322494507秒
程序运行时间:23.977590322494507秒
程序运行时间:23.977590322494507秒
程序运行时间:23.978590965270996秒
程序运行时间:23.978590965270996秒
程序运行时间:23.979591131210327秒
程序运行时间:23.979591131210327秒
程序运行时间:23.979591131210327秒
程序运行时间:23.980591297149658秒
程序运行时间:23.980591297149658秒
程序运行时间:23.98159170150757秒
程序运行时间:23.98159170150757秒
程序运行时间:23.9825918674469秒
程序运行时间:23.9825918674469秒
程序运行时间:23.983592987060547秒
程序运行时间:23.983592987060547秒
程序运行时间:23.984591484069824秒
程序运行时间:23.984591484069824秒
程序运行时间:23.984591484069824秒
程序运行时间:23.98559260368347秒
程序运行时间:23.98559260368347秒
程序运行时间:23.9865939617157秒
程序运行时间:23.987592935562134秒
程序运行时间:23.987592935562134秒
程序运行时间:23.987592935562134秒
程序运行时间:23.98859453201294秒
程序运行时间:23.98859453201294秒
程序运行时间:23.989593267440796秒
程序运行时间:23.989593267440796秒

    lineName  direction      idx1      idx2 win_st  distance  \
0      M2333        1.0  BS00047D  BS00047D    372  0.000744
1      M2333        1.0  BS00027D  BS00027D    380  0.009197
2      M2333        1.0  BS00027D  BS00027D    384  0.007580
15     M2333        1.0  BS00027D  BS00047D    404  0.005349
16     M2333        1.0  BS00027D  BS00027D    408  0.009226
..       ...        ...       ...       ...    ...       ...
480    M2333        2.0  BS04317D  BS00047D   1340  0.009441
482    M2333        2.0  BS04317D  BS00027D   1356  0.007390
486    M2333        2.0  BS04317D  BS00047D   1364  0.005367
487    M2333        2.0  BS04317D  BS00047D   1368  0.006891
488    M2333        2.0  BS04317D  BS00047D   1368  0.006269

             start_time            end_time        duration
0   2019-01-04 09:16:07 2019-01-04 09:19:55 0 days 00:03:48
1   2019-01-04 16:16:06 2019-01-04 16:19:56 0 days 00:03:50
2   2019-01-04 17:36:04 2019-01-04 17:39:56 0 days 00:03:52
15  2019-01-04 17:36:01 2019-01-04 17:39:53 0 days 00:03:52
16  2019-01-04 18:20:01 2019-01-04 18:23:58 0 days 00:03:57
..                  ...                 ...             ...
480 2019-01-04 09:00:20 2019-01-04 09:03:30 0 days 00:03:10
482 2019-01-04 14:44:02 2019-01-04 14:47:51 0 days 00:03:49
486 2019-01-04 08:00:01 2019-01-04 08:03:38 0 days 00:03:37
487 2019-01-04 09:04:11 2019-01-04 09:07:58 0 days 00:03:47
488 2019-01-04 09:08:08 2019-01-04 09:11:51 0 days 00:03:43

[268 rows x 9 columns]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_21272\1082889789.py:121: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_event['end_time'] = next_event['end_time']
C:\Users\ASUS\AppData\Local\Temp\ipykernel_21272\1082889789.py:122: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_event['duration'] = current_event['end_time'] - current_event['start_time']
C:\Users\ASUS\AppData\Local\Temp\ipykernel_21272\1082889789.py:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  current_event['win_st'] = f"{current_event['win_st']},{next_event['win_st']}"